//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbManager
{
    using System;
    using System.Runtime.Serialization;
    using System.Data;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using System.Transactions;
    using SoftBand.EntityManager;
    
    
    // Table('AspNetRoles') Entity class
    // Do not add or change code here.
    [System.Serializable()]
    public partial class AspNetRole : SoftBand.EntityManager.Entity
    {
        
        public AspNetRole()
        {
            this.DefineColumns(4);
        }
        
        public string Id
        {
            get
            {
                return ((string)(this[0]));
            }
            set
            {
                this[0] = value;
            }
        }
        
        public string Name
        {
            get
            {
                return ((string)(this[1]));
            }
            set
            {
                this[1] = value;
            }
        }
        
        public string NormalizedName
        {
            get
            {
                return ((string)(this.IsnullZeroOrNull(2, typeof(string))));
            }
            set
            {
                this[2] = value;
            }
        }
        
        public string ConcurrencyStamp
        {
            get
            {
                return ((string)(this.IsnullZeroOrNull(3, typeof(string))));
            }
            set
            {
                this[3] = value;
            }
        }
        
        public static AspNetRoleService Service
        {
            get
            {
                return ((AspNetRoleService)(GetServiceObject(typeof(AspNetRole), typeof(AspNetRoleService))));
            }
        }
        
        public bool IsNormalizedNameNull()
        {
            return this.IsNull(2);
        }
        
        public void SetNormalizedNameToNull()
        {
            this[2] = System.DBNull.Value;
        }
        
        public bool IsConcurrencyStampNull()
        {
            return this.IsNull(3);
        }
        
        public void SetConcurrencyStampToNull()
        {
            this[3] = System.DBNull.Value;
        }
        
        public static AspNetRoleSet GetAll()
        {
            return Service.GetAll();
        }
        
        public static string GetAllJson()
        {
            return Service.GetAllJson();
        }
        
        public static async Task<AspNetRoleSet> GetAllAsync()
        {
            return await Service.GetAllAsync();
        }
        
        public static async Task<string> GetAllJsonAsync()
        {
            return await Service.GetAllJsonAsync();
        }
        
        public static AspNetRole GetByKey(string id)
        {
            return Service.GetByKey(id);
        }
        
        public static string GetByKeyJson(string id)
        {
            return Service.GetByKeyJson(id);
        }
        
        public static async Task<AspNetRole> GetByKeyAsync(string id)
        {
            return await Service.GetByKeyAsync(id);
        }
        
        public static async Task<string> GetByKeyJsonAsync(string id)
        {
            return await Service.GetByKeyJsonAsync(id);
        }
        
        public static AspNetRole Insert(string id, string name, object normalizedName, object concurrencyStamp)
        {
            // Insert 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            if ((normalizedName == null))
            {
                normalizedName = System.DBNull.Value;
            }
            if ((concurrencyStamp == null))
            {
                concurrencyStamp = System.DBNull.Value;
            }
            return Service.Insert(id, name, normalizedName, concurrencyStamp);
        }
        
        public static async Task<AspNetRole> InsertAsync(string id, string name, object normalizedName, object concurrencyStamp)
        {
            // InsertAsync 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            if ((normalizedName == null))
            {
                normalizedName = System.DBNull.Value;
            }
            if ((concurrencyStamp == null))
            {
                concurrencyStamp = System.DBNull.Value;
            }
            return await Service.InsertAsync(id, name, normalizedName, concurrencyStamp);
        }
        
        public new AspNetRole Insert()
        {
            // Insert 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            return Insert(Id, Name, NormalizedName, ConcurrencyStamp);
        }
        
        public async Task<AspNetRole> InsertAsync()
        {
            // Insert 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            return await InsertAsync(Id, Name, NormalizedName, ConcurrencyStamp);
        }
        
        public new int Update()
        {
            // 인수를 해당 파라메타에 옮긴다
            string idParam = this.Id;
            string nameParam = this.Name;
            object normalizedNameParam;
            if ((this.IsNormalizedNameNull() == false))
            {
                normalizedNameParam = this.NormalizedName;
            }
            else
            {
                normalizedNameParam = System.DBNull.Value;
            }
            object concurrencyStampParam;
            if ((this.IsConcurrencyStampNull() == false))
            {
                concurrencyStampParam = this.ConcurrencyStamp;
            }
            else
            {
                concurrencyStampParam = System.DBNull.Value;
            }
            // update 실행
            return Service.Update(idParam, nameParam, normalizedNameParam, concurrencyStampParam);
        }
        
        public async Task<int> UpdateAsync()
        {
            // 인수를 해당 파라메타에 옮긴다
            string idParam = this.Id;
            string nameParam = this.Name;
            object normalizedNameParam;
            if ((this.IsNormalizedNameNull() == false))
            {
                normalizedNameParam = this.NormalizedName;
            }
            else
            {
                normalizedNameParam = System.DBNull.Value;
            }
            object concurrencyStampParam;
            if ((this.IsConcurrencyStampNull() == false))
            {
                concurrencyStampParam = this.ConcurrencyStamp;
            }
            else
            {
                concurrencyStampParam = System.DBNull.Value;
            }
            return await Service.UpdateAsync(idParam, nameParam, normalizedNameParam, concurrencyStampParam);
        }
        
        public static int Update(string id, string name, object normalizedName, object concurrencyStamp)
        {
            if ((normalizedName == null))
            {
                normalizedName = System.DBNull.Value;
            }
            if ((concurrencyStamp == null))
            {
                concurrencyStamp = System.DBNull.Value;
            }
            return Service.Update(id, name, normalizedName, concurrencyStamp);
        }
        
        public static async Task<int> UpdateAsync(string id, string name, object normalizedName, object concurrencyStamp)
        {
            if ((normalizedName == null))
            {
                normalizedName = System.DBNull.Value;
            }
            if ((concurrencyStamp == null))
            {
                concurrencyStamp = System.DBNull.Value;
            }
            return await Service.UpdateAsync(id, name, normalizedName, concurrencyStamp);
        }
        
        public static int Delete(string id)
        {
            return Service.Delete(id);
        }
        
        public static async Task<int> DeleteAsync(string id)
        {
            return await Service.DeleteAsync(id);
        }
        
        public new int Delete()
        {
            return Service.Delete(Id);
        }
        
        public async Task<int> DeleteAsync()
        {
            return await Service.DeleteAsync(Id);
        }
    }
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbManager
{
    using System;
    using System.Runtime.Serialization;
    using System.Data;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using System.Transactions;
    using SoftBand.EntityManager;
    
    
    // Table('AspNetRoles')  Service class
    // Do not add or change code here.
    public partial class AspNetRoleService : SoftBand.EntityManager.Service
    {
        
        public AspNetRoleSet GetAll()
        {
            return ((AspNetRoleSet)(this.GetAll("AspNetRoles", typeof(AspNetRoleSet))));
        }
        
        public string GetAllJson()
        {
            return this.GetAllJson("AspNetRoles");
        }
        
        public async Task<AspNetRoleSet> GetAllAsync()
        {
            return ((AspNetRoleSet)(await this.GetAllAsync("AspNetRoles", typeof(AspNetRoleSet))));
        }
        
        public async Task<string> GetAllJsonAsync()
        {
            return await this.GetAllJsonAsync("AspNetRoles");
        }
        
        public AspNetRole GetByKey(string id)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM AspNetRoles WHERE Id = @id";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "id";
            AddParameters(selectCmd, paraNames, id);
            // 
            AspNetRole entity = ((AspNetRole)(this.GetEntity(selectCmd, typeof(AspNetRoleSet))));
            selectCmd.Dispose();
            return entity;
        }
        
        public  string GetByKeyJson(string id)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM AspNetRoles WHERE Id = @id";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "id";
            AddParameters(selectCmd, paraNames, id);
            // 
            return this.GetJsonDataSet(selectCmd);
        }
        
        public async Task<AspNetRole> GetByKeyAsync(string id)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM AspNetRoles WHERE Id = @id";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "id";
            AddParameters(selectCmd, paraNames, id);
            // 
            // GetByKeyAsync 를 호출한다
            AspNetRole entity = ((AspNetRole)(await this.GetEntityAsync(selectCmd, typeof(AspNetRoleSet))));
            selectCmd.Dispose();
            return entity;
        }
        
        public async Task<string> GetByKeyJsonAsync(string id)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM AspNetRoles WHERE Id = @id";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "id";
            AddParameters(selectCmd, paraNames, id);
            // 
            return await this.GetJsonDataSetAsync(selectCmd);
        }
        
        public AspNetRole Insert(string id, string name, object normalizedName, object concurrencyStamp)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand insertCommand = DbCommandFactory.CreateDbCommand();
            insertCommand.CommandText = "INSERT INTO AspNetRoles(Id, Name, NormalizedName, ConcurrencyStamp) VALUES (@id, " +
                "@name, @normalizedName, @concurrencyStamp) ";
            insertCommand.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "id,name,normalizedName,concurrencyStamp";
            AddParameters(insertCommand, paraNames, id, name, normalizedName, concurrencyStamp);
            // 
            // Insert 를 호출한다
            this.ExecuteNonQuery(insertCommand);
            AspNetRole entity = ((AspNetRole)(this.GetByKey(id)));
            insertCommand.Dispose();
            return entity;
        }
        
        public async Task<AspNetRole> InsertAsync(string id, string name, object normalizedName, object concurrencyStamp)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand insertCommand = DbCommandFactory.CreateDbCommand();
            insertCommand.CommandText = "INSERT INTO AspNetRoles(Id, Name, NormalizedName, ConcurrencyStamp) VALUES (@id, " +
                "@name, @normalizedName, @concurrencyStamp) ";
            insertCommand.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "id,name,normalizedName,concurrencyStamp";
            AddParameters(insertCommand, paraNames, id, name, normalizedName, concurrencyStamp);
            // 
            // InsertAsync 를 호출한다
            await this.ExecuteNonQueryAsync(insertCommand);
            AspNetRole entity = ((AspNetRole)(await this.GetByKeyAsync(id)));
            insertCommand.Dispose();
            return entity;
        }
        
        public int Update(string id, string name, object normalizedName, object concurrencyStamp)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand updateCmd = DbCommandFactory.CreateDbCommand();
            updateCmd.CommandText = "UPDATE AspNetRoles SET Name = @name, NormalizedName = @normalizedName, Concurrenc" +
                "yStamp = @concurrencyStamp WHERE Id = @id";
            updateCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "id,name,normalizedName,concurrencyStamp";
            AddParameters(updateCmd, paraNames, id, name, normalizedName, concurrencyStamp);
            // 
            // Update 를 호출한다
            int executeCnt = this.ExecuteNonQuery(updateCmd);
            updateCmd.Dispose();
            return executeCnt;
        }
        
        public async Task<int> UpdateAsync(string id, string name, object normalizedName, object concurrencyStamp)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand updateCmd = DbCommandFactory.CreateDbCommand();
            updateCmd.CommandText = "UPDATE AspNetRoles SET Name = @name, NormalizedName = @normalizedName, Concurrenc" +
                "yStamp = @concurrencyStamp WHERE Id = @id";
            updateCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "id,name,normalizedName,concurrencyStamp";
            AddParameters(updateCmd, paraNames, id, name, normalizedName, concurrencyStamp);
            // 
            // Update 를 호출한다
            int executeCnt = await this.ExecuteNonQueryAsync(updateCmd);
            updateCmd.Dispose();
            return executeCnt;
        }
        
        public int Delete(string id)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand deleteCmd = DbCommandFactory.CreateDbCommand();
            deleteCmd.CommandText = "DELETE FROM AspNetRoles WHERE Id = @id";
            deleteCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "id";
            AddParameters(deleteCmd, paraNames, id);
            // 
            // Delete 를 호출한다
            int executeCnt = this.ExecuteNonQuery(deleteCmd);
            deleteCmd.Dispose();
            return executeCnt;
        }
        
        public async Task<int> DeleteAsync(string id)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand deleteCmd = DbCommandFactory.CreateDbCommand();
            deleteCmd.CommandText = "DELETE FROM AspNetRoles WHERE Id = @id";
            deleteCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "id";
            AddParameters(deleteCmd, paraNames, id);
            // 
            // Delete 를 호출한다
            int executeCnt = await this.ExecuteNonQueryAsync(deleteCmd);
            deleteCmd.Dispose();
            return executeCnt;
        }
    }
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbManager
{
    using System;
    using System.Runtime.Serialization;
    using System.Data;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using System.Transactions;
    using SoftBand.EntityManager;
    
    
    // Table('AspNetRoles') EntitySet class
    // Do not add or change code here.
    [System.Serializable()]
    public partial class AspNetRoleSet : SoftBand.EntityManager.EntitySet, System.Collections.IEnumerable
    {
        
        // Constructor
        public AspNetRoleSet() : 
                this(null)
        {
        }
        
        // basic constructor
        protected AspNetRoleSet(object state)
        {
            this.Setup();
        }
        
        // remoting constructor...
        protected AspNetRoleSet(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context)
        {
            this.Setup();
        }
        
        public AspNetRoleBoundCollection Entities
        {
            get
            {
                return this.GetBoundCollection();
            }
        }
        
        // shared object initialization...
        private void Setup()
        {
            this.EntityType = typeof(AspNetRole);
        }
        
        private AspNetRoleBoundCollection GetBoundCollection()
        {
            return this.GetBoundCollection(0);
        }
        
        private AspNetRoleBoundCollection GetBoundCollection(int tableIndex)
        {
            return ((AspNetRoleBoundCollection)(this.GetBoundCollection(this, tableIndex, typeof(AspNetRoleBoundCollection))));
        }
        
        public partial class AspNetRoleBoundCollection : SoftBand.EntityManager.EntityBoundCollection
        {
            
            public new AspNetRole this[int index]
            {
                get
                {
                    return ((AspNetRole)(this.EntitySet.GetEntity(this.TableIndex, index)));
                }
            }
        }
    }
}
