//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbManager
{
    using System;
    using System.Runtime.Serialization;
    using System.Data;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using System.Transactions;
    using SoftBand.EntityManager;
    
    
    // Table('AspNetUserLogins') Entity class
    // Do not add or change code here.
    [System.Serializable()]
    public partial class AspNetUserLogin : SoftBand.EntityManager.Entity
    {
        
        public AspNetUserLogin()
        {
            this.DefineColumns(4);
        }
        
        public string LofinProvider
        {
            get
            {
                return ((string)(this[0]));
            }
            set
            {
                this[0] = value;
            }
        }
        
        public string ProviderKey
        {
            get
            {
                return ((string)(this[1]));
            }
            set
            {
                this[1] = value;
            }
        }
        
        public string ProviderDisplayName
        {
            get
            {
                return ((string)(this.IsnullZeroOrNull(2, typeof(string))));
            }
            set
            {
                this[2] = value;
            }
        }
        
        public string UserId
        {
            get
            {
                return ((string)(this[3]));
            }
            set
            {
                this[3] = value;
            }
        }
        
        public static AspNetUserLoginService Service
        {
            get
            {
                return ((AspNetUserLoginService)(GetServiceObject(typeof(AspNetUserLogin), typeof(AspNetUserLoginService))));
            }
        }
        
        public bool IsProviderDisplayNameNull()
        {
            return this.IsNull(2);
        }
        
        public void SetProviderDisplayNameToNull()
        {
            this[2] = System.DBNull.Value;
        }
        
        public static AspNetUserLoginSet GetAll()
        {
            return Service.GetAll();
        }
        
        public static string GetAllJson()
        {
            return Service.GetAllJson();
        }
        
        public static async Task<AspNetUserLoginSet> GetAllAsync()
        {
            return await Service.GetAllAsync();
        }
        
        public static async Task<string> GetAllJsonAsync()
        {
            return await Service.GetAllJsonAsync();
        }
        
        public static AspNetUserLoginSet GetForAspNetUsers(string userId)
        {
            return Service.GetForAspNetUsers(userId);
        }
        
        public static async Task<AspNetUserLoginSet> GetForAspNetUsersAsync(string userId)
        {
            return await Service.GetForAspNetUsersAsync(userId);
        }
        
        public static string GetForAspNetUsersJson(string userId)
        {
            return Service.GetForAspNetUsersJson(userId);
        }
        
        public static async Task<string> GetForAspNetUsersJsonAsync(string userId)
        {
            return await Service.GetForAspNetUsersJsonAsync(userId);
        }
        
        public static AspNetUserLogin GetByKey(string lofinProvider, string providerKey)
        {
            return Service.GetByKey(lofinProvider, providerKey);
        }
        
        public static string GetByKeyJson(string lofinProvider, string providerKey)
        {
            return Service.GetByKeyJson(lofinProvider, providerKey);
        }
        
        public static async Task<AspNetUserLogin> GetByKeyAsync(string lofinProvider, string providerKey)
        {
            return await Service.GetByKeyAsync(lofinProvider, providerKey);
        }
        
        public static async Task<string> GetByKeyJsonAsync(string lofinProvider, string providerKey)
        {
            return await Service.GetByKeyJsonAsync(lofinProvider, providerKey);
        }
        
        public static AspNetUserLogin Insert(string lofinProvider, string providerKey, object providerDisplayName, string userId)
        {
            // Insert 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            if ((providerDisplayName == null))
            {
                providerDisplayName = System.DBNull.Value;
            }
            return Service.Insert(lofinProvider, providerKey, providerDisplayName, userId);
        }
        
        public static async Task<AspNetUserLogin> InsertAsync(string lofinProvider, string providerKey, object providerDisplayName, string userId)
        {
            // InsertAsync 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            if ((providerDisplayName == null))
            {
                providerDisplayName = System.DBNull.Value;
            }
            return await Service.InsertAsync(lofinProvider, providerKey, providerDisplayName, userId);
        }
        
        public new AspNetUserLogin Insert()
        {
            // Insert 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            return Insert(LofinProvider, ProviderKey, ProviderDisplayName, UserId);
        }
        
        public async Task<AspNetUserLogin> InsertAsync()
        {
            // Insert 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            return await InsertAsync(LofinProvider, ProviderKey, ProviderDisplayName, UserId);
        }
        
        public new int Update()
        {
            // 인수를 해당 파라메타에 옮긴다
            string lofinProviderParam = this.LofinProvider;
            string providerKeyParam = this.ProviderKey;
            object providerDisplayNameParam;
            if ((this.IsProviderDisplayNameNull() == false))
            {
                providerDisplayNameParam = this.ProviderDisplayName;
            }
            else
            {
                providerDisplayNameParam = System.DBNull.Value;
            }
            string userIdParam = this.UserId;
            // update 실행
            return Service.Update(lofinProviderParam, providerKeyParam, providerDisplayNameParam, userIdParam);
        }
        
        public async Task<int> UpdateAsync()
        {
            // 인수를 해당 파라메타에 옮긴다
            string lofinProviderParam = this.LofinProvider;
            string providerKeyParam = this.ProviderKey;
            object providerDisplayNameParam;
            if ((this.IsProviderDisplayNameNull() == false))
            {
                providerDisplayNameParam = this.ProviderDisplayName;
            }
            else
            {
                providerDisplayNameParam = System.DBNull.Value;
            }
            string userIdParam = this.UserId;
            return await Service.UpdateAsync(lofinProviderParam, providerKeyParam, providerDisplayNameParam, userIdParam);
        }
        
        public static int Update(string lofinProvider, string providerKey, object providerDisplayName, string userId)
        {
            if ((providerDisplayName == null))
            {
                providerDisplayName = System.DBNull.Value;
            }
            return Service.Update(lofinProvider, providerKey, providerDisplayName, userId);
        }
        
        public static async Task<int> UpdateAsync(string lofinProvider, string providerKey, object providerDisplayName, string userId)
        {
            if ((providerDisplayName == null))
            {
                providerDisplayName = System.DBNull.Value;
            }
            return await Service.UpdateAsync(lofinProvider, providerKey, providerDisplayName, userId);
        }
        
        public static int Delete(string lofinProvider, string providerKey)
        {
            return Service.Delete(lofinProvider, providerKey);
        }
        
        public static async Task<int> DeleteAsync(string lofinProvider, string providerKey)
        {
            return await Service.DeleteAsync(lofinProvider, providerKey);
        }
        
        public new int Delete()
        {
            return Service.Delete(LofinProvider, ProviderKey);
        }
        
        public async Task<int> DeleteAsync()
        {
            return await Service.DeleteAsync(LofinProvider, ProviderKey);
        }
    }
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbManager
{
    using System;
    using System.Runtime.Serialization;
    using System.Data;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using System.Transactions;
    using SoftBand.EntityManager;
    
    
    // Table('AspNetUserLogins')  Service class
    // Do not add or change code here.
    public partial class AspNetUserLoginService : SoftBand.EntityManager.Service
    {
        
        public AspNetUserLoginSet GetAll()
        {
            return ((AspNetUserLoginSet)(this.GetAll("AspNetUserLogins", typeof(AspNetUserLoginSet))));
        }
        
        public string GetAllJson()
        {
            return this.GetAllJson("AspNetUserLogins");
        }
        
        public async Task<AspNetUserLoginSet> GetAllAsync()
        {
            return ((AspNetUserLoginSet)(await this.GetAllAsync("AspNetUserLogins", typeof(AspNetUserLoginSet))));
        }
        
        public async Task<string> GetAllJsonAsync()
        {
            return await this.GetAllJsonAsync("AspNetUserLogins");
        }
        
        public AspNetUserLoginSet GetForAspNetUsers(string userId)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [AspNetUserLogins] WHERE UserId = @userId";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "userId";
            AddParameters(selectCmd, paraNames, userId);
            AspNetUserLoginSet entitySet = ((AspNetUserLoginSet)(this.GetEntitySet(selectCmd, typeof(AspNetUserLoginSet))));
            selectCmd.Dispose();
            return entitySet;
        }
        
        public async Task<AspNetUserLoginSet> GetForAspNetUsersAsync(string userId)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [AspNetUserLogins] WHERE UserId = @userId";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "userId";
            AddParameters(selectCmd, paraNames, userId);
            AspNetUserLoginSet entitySet = ((AspNetUserLoginSet)(await this.GetEntitySetAsync(selectCmd, typeof(AspNetUserLoginSet))));
            selectCmd.Dispose();
            return entitySet;
        }
        
        public string GetForAspNetUsersJson(string userId)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [AspNetUserLogins] WHERE UserId = @userId";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "userId";
            AddParameters(selectCmd, paraNames, userId);
            return  this.GetJsonDataSet(selectCmd);
        }
        
        public async Task<string> GetForAspNetUsersJsonAsync(string userId)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [AspNetUserLogins] WHERE UserId = @userId";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "userId";
            AddParameters(selectCmd, paraNames, userId);
            return await this.GetJsonDataSetAsync(selectCmd);
        }
        
        public AspNetUserLogin GetByKey(string lofinProvider, string providerKey)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM AspNetUserLogins WHERE LofinProvider = @lofinProvider AND ProviderK" +
                "ey = @providerKey";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "lofinProvider,providerKey";
            AddParameters(selectCmd, paraNames, lofinProvider, providerKey);
            // 
            AspNetUserLogin entity = ((AspNetUserLogin)(this.GetEntity(selectCmd, typeof(AspNetUserLoginSet))));
            selectCmd.Dispose();
            return entity;
        }
        
        public  string GetByKeyJson(string lofinProvider, string providerKey)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM AspNetUserLogins WHERE LofinProvider = @lofinProvider AND ProviderK" +
                "ey = @providerKey";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "lofinProvider,providerKey";
            AddParameters(selectCmd, paraNames, lofinProvider, providerKey);
            // 
            return this.GetJsonDataSet(selectCmd);
        }
        
        public async Task<AspNetUserLogin> GetByKeyAsync(string lofinProvider, string providerKey)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM AspNetUserLogins WHERE LofinProvider = @lofinProvider AND ProviderK" +
                "ey = @providerKey";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "lofinProvider,providerKey";
            AddParameters(selectCmd, paraNames, lofinProvider, providerKey);
            // 
            // GetByKeyAsync 를 호출한다
            AspNetUserLogin entity = ((AspNetUserLogin)(await this.GetEntityAsync(selectCmd, typeof(AspNetUserLoginSet))));
            selectCmd.Dispose();
            return entity;
        }
        
        public async Task<string> GetByKeyJsonAsync(string lofinProvider, string providerKey)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM AspNetUserLogins WHERE LofinProvider = @lofinProvider AND ProviderK" +
                "ey = @providerKey";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "lofinProvider,providerKey";
            AddParameters(selectCmd, paraNames, lofinProvider, providerKey);
            // 
            return await this.GetJsonDataSetAsync(selectCmd);
        }
        
        public AspNetUserLogin Insert(string lofinProvider, string providerKey, object providerDisplayName, string userId)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand insertCommand = DbCommandFactory.CreateDbCommand();
            insertCommand.CommandText = "INSERT INTO AspNetUserLogins(LofinProvider, ProviderKey, ProviderDisplayName, Use" +
                "rId) VALUES (@lofinProvider, @providerKey, @providerDisplayName, @userId) ";
            insertCommand.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "lofinProvider,providerKey,providerDisplayName,userId";
            AddParameters(insertCommand, paraNames, lofinProvider, providerKey, providerDisplayName, userId);
            // 
            // Insert 를 호출한다
            this.ExecuteNonQuery(insertCommand);
            AspNetUserLogin entity = ((AspNetUserLogin)(this.GetByKey(lofinProvider, providerKey)));
            insertCommand.Dispose();
            return entity;
        }
        
        public async Task<AspNetUserLogin> InsertAsync(string lofinProvider, string providerKey, object providerDisplayName, string userId)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand insertCommand = DbCommandFactory.CreateDbCommand();
            insertCommand.CommandText = "INSERT INTO AspNetUserLogins(LofinProvider, ProviderKey, ProviderDisplayName, Use" +
                "rId) VALUES (@lofinProvider, @providerKey, @providerDisplayName, @userId) ";
            insertCommand.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "lofinProvider,providerKey,providerDisplayName,userId";
            AddParameters(insertCommand, paraNames, lofinProvider, providerKey, providerDisplayName, userId);
            // 
            // InsertAsync 를 호출한다
            await this.ExecuteNonQueryAsync(insertCommand);
            AspNetUserLogin entity = ((AspNetUserLogin)(await this.GetByKeyAsync(lofinProvider, providerKey)));
            insertCommand.Dispose();
            return entity;
        }
        
        public int Update(string lofinProvider, string providerKey, object providerDisplayName, string userId)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand updateCmd = DbCommandFactory.CreateDbCommand();
            updateCmd.CommandText = "UPDATE AspNetUserLogins SET ProviderDisplayName = @providerDisplayName, UserId = " +
                "@userId WHERE LofinProvider = @lofinProvider AND ProviderKey = @providerKey";
            updateCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "lofinProvider,providerKey,providerDisplayName,userId";
            AddParameters(updateCmd, paraNames, lofinProvider, providerKey, providerDisplayName, userId);
            // 
            // Update 를 호출한다
            int executeCnt = this.ExecuteNonQuery(updateCmd);
            updateCmd.Dispose();
            return executeCnt;
        }
        
        public async Task<int> UpdateAsync(string lofinProvider, string providerKey, object providerDisplayName, string userId)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand updateCmd = DbCommandFactory.CreateDbCommand();
            updateCmd.CommandText = "UPDATE AspNetUserLogins SET ProviderDisplayName = @providerDisplayName, UserId = " +
                "@userId WHERE LofinProvider = @lofinProvider AND ProviderKey = @providerKey";
            updateCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "lofinProvider,providerKey,providerDisplayName,userId";
            AddParameters(updateCmd, paraNames, lofinProvider, providerKey, providerDisplayName, userId);
            // 
            // Update 를 호출한다
            int executeCnt = await this.ExecuteNonQueryAsync(updateCmd);
            updateCmd.Dispose();
            return executeCnt;
        }
        
        public int Delete(string lofinProvider, string providerKey)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand deleteCmd = DbCommandFactory.CreateDbCommand();
            deleteCmd.CommandText = "DELETE FROM AspNetUserLogins WHERE LofinProvider = @lofinProvider AND ProviderKey" +
                " = @providerKey";
            deleteCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "lofinProvider,providerKey";
            AddParameters(deleteCmd, paraNames, lofinProvider, providerKey);
            // 
            // Delete 를 호출한다
            int executeCnt = this.ExecuteNonQuery(deleteCmd);
            deleteCmd.Dispose();
            return executeCnt;
        }
        
        public async Task<int> DeleteAsync(string lofinProvider, string providerKey)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand deleteCmd = DbCommandFactory.CreateDbCommand();
            deleteCmd.CommandText = "DELETE FROM AspNetUserLogins WHERE LofinProvider = @lofinProvider AND ProviderKey" +
                " = @providerKey";
            deleteCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "lofinProvider,providerKey";
            AddParameters(deleteCmd, paraNames, lofinProvider, providerKey);
            // 
            // Delete 를 호출한다
            int executeCnt = await this.ExecuteNonQueryAsync(deleteCmd);
            deleteCmd.Dispose();
            return executeCnt;
        }
    }
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbManager
{
    using System;
    using System.Runtime.Serialization;
    using System.Data;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using System.Transactions;
    using SoftBand.EntityManager;
    
    
    // Table('AspNetUserLogins') EntitySet class
    // Do not add or change code here.
    [System.Serializable()]
    public partial class AspNetUserLoginSet : SoftBand.EntityManager.EntitySet, System.Collections.IEnumerable
    {
        
        // Constructor
        public AspNetUserLoginSet() : 
                this(null)
        {
        }
        
        // basic constructor
        protected AspNetUserLoginSet(object state)
        {
            this.Setup();
        }
        
        // remoting constructor...
        protected AspNetUserLoginSet(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context)
        {
            this.Setup();
        }
        
        public AspNetUserLoginBoundCollection Entities
        {
            get
            {
                return this.GetBoundCollection();
            }
        }
        
        // shared object initialization...
        private void Setup()
        {
            this.EntityType = typeof(AspNetUserLogin);
        }
        
        private AspNetUserLoginBoundCollection GetBoundCollection()
        {
            return this.GetBoundCollection(0);
        }
        
        private AspNetUserLoginBoundCollection GetBoundCollection(int tableIndex)
        {
            return ((AspNetUserLoginBoundCollection)(this.GetBoundCollection(this, tableIndex, typeof(AspNetUserLoginBoundCollection))));
        }
        
        public partial class AspNetUserLoginBoundCollection : SoftBand.EntityManager.EntityBoundCollection
        {
            
            public new AspNetUserLogin this[int index]
            {
                get
                {
                    return ((AspNetUserLogin)(this.EntitySet.GetEntity(this.TableIndex, index)));
                }
            }
        }
    }
}
