//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbManager
{
    using System;
    using System.Runtime.Serialization;
    using System.Data;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using System.Transactions;
    using SoftBand.EntityManager;
    
    
    // Table('AspNetUserTokens') Entity class
    // Do not add or change code here.
    [System.Serializable()]
    public partial class AspNetUserToken : SoftBand.EntityManager.Entity
    {
        
        public AspNetUserToken()
        {
            this.DefineColumns(4);
        }
        
        public string Id
        {
            get
            {
                return ((string)(this[0]));
            }
            set
            {
                this[0] = value;
            }
        }
        
        public string UserId
        {
            get
            {
                return ((string)(this[1]));
            }
            set
            {
                this[1] = value;
            }
        }
        
        public string ClaimType
        {
            get
            {
                return ((string)(this.IsnullZeroOrNull(2, typeof(string))));
            }
            set
            {
                this[2] = value;
            }
        }
        
        public string ClaimValue
        {
            get
            {
                return ((string)(this.IsnullZeroOrNull(3, typeof(string))));
            }
            set
            {
                this[3] = value;
            }
        }
        
        public static AspNetUserTokenService Service
        {
            get
            {
                return ((AspNetUserTokenService)(GetServiceObject(typeof(AspNetUserToken), typeof(AspNetUserTokenService))));
            }
        }
        
        public bool IsClaimTypeNull()
        {
            return this.IsNull(2);
        }
        
        public void SetClaimTypeToNull()
        {
            this[2] = System.DBNull.Value;
        }
        
        public bool IsClaimValueNull()
        {
            return this.IsNull(3);
        }
        
        public void SetClaimValueToNull()
        {
            this[3] = System.DBNull.Value;
        }
        
        public static AspNetUserTokenSet GetAll()
        {
            return Service.GetAll();
        }
        
        public static string GetAllJson()
        {
            return Service.GetAllJson();
        }
        
        public static async Task<AspNetUserTokenSet> GetAllAsync()
        {
            return await Service.GetAllAsync();
        }
        
        public static async Task<string> GetAllJsonAsync()
        {
            return await Service.GetAllJsonAsync();
        }
        
        public static AspNetUserTokenSet GetForAspNetUsers(string userId)
        {
            return Service.GetForAspNetUsers(userId);
        }
        
        public static async Task<AspNetUserTokenSet> GetForAspNetUsersAsync(string userId)
        {
            return await Service.GetForAspNetUsersAsync(userId);
        }
        
        public static string GetForAspNetUsersJson(string userId)
        {
            return Service.GetForAspNetUsersJson(userId);
        }
        
        public static async Task<string> GetForAspNetUsersJsonAsync(string userId)
        {
            return await Service.GetForAspNetUsersJsonAsync(userId);
        }
        
        public static AspNetUserToken GetByKey(string id)
        {
            return Service.GetByKey(id);
        }
        
        public static string GetByKeyJson(string id)
        {
            return Service.GetByKeyJson(id);
        }
        
        public static async Task<AspNetUserToken> GetByKeyAsync(string id)
        {
            return await Service.GetByKeyAsync(id);
        }
        
        public static async Task<string> GetByKeyJsonAsync(string id)
        {
            return await Service.GetByKeyJsonAsync(id);
        }
        
        public static AspNetUserToken Insert(string id, string userId, object claimType, object claimValue)
        {
            // Insert 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            if ((claimType == null))
            {
                claimType = System.DBNull.Value;
            }
            if ((claimValue == null))
            {
                claimValue = System.DBNull.Value;
            }
            return Service.Insert(id, userId, claimType, claimValue);
        }
        
        public static async Task<AspNetUserToken> InsertAsync(string id, string userId, object claimType, object claimValue)
        {
            // InsertAsync 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            if ((claimType == null))
            {
                claimType = System.DBNull.Value;
            }
            if ((claimValue == null))
            {
                claimValue = System.DBNull.Value;
            }
            return await Service.InsertAsync(id, userId, claimType, claimValue);
        }
        
        public new AspNetUserToken Insert()
        {
            // Insert 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            return Insert(Id, UserId, ClaimType, ClaimValue);
        }
        
        public async Task<AspNetUserToken> InsertAsync()
        {
            // Insert 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            return await InsertAsync(Id, UserId, ClaimType, ClaimValue);
        }
        
        public new int Update()
        {
            // 인수를 해당 파라메타에 옮긴다
            string idParam = this.Id;
            string userIdParam = this.UserId;
            object claimTypeParam;
            if ((this.IsClaimTypeNull() == false))
            {
                claimTypeParam = this.ClaimType;
            }
            else
            {
                claimTypeParam = System.DBNull.Value;
            }
            object claimValueParam;
            if ((this.IsClaimValueNull() == false))
            {
                claimValueParam = this.ClaimValue;
            }
            else
            {
                claimValueParam = System.DBNull.Value;
            }
            // update 실행
            return Service.Update(idParam, userIdParam, claimTypeParam, claimValueParam);
        }
        
        public async Task<int> UpdateAsync()
        {
            // 인수를 해당 파라메타에 옮긴다
            string idParam = this.Id;
            string userIdParam = this.UserId;
            object claimTypeParam;
            if ((this.IsClaimTypeNull() == false))
            {
                claimTypeParam = this.ClaimType;
            }
            else
            {
                claimTypeParam = System.DBNull.Value;
            }
            object claimValueParam;
            if ((this.IsClaimValueNull() == false))
            {
                claimValueParam = this.ClaimValue;
            }
            else
            {
                claimValueParam = System.DBNull.Value;
            }
            return await Service.UpdateAsync(idParam, userIdParam, claimTypeParam, claimValueParam);
        }
        
        public static int Update(string id, string userId, object claimType, object claimValue)
        {
            if ((claimType == null))
            {
                claimType = System.DBNull.Value;
            }
            if ((claimValue == null))
            {
                claimValue = System.DBNull.Value;
            }
            return Service.Update(id, userId, claimType, claimValue);
        }
        
        public static async Task<int> UpdateAsync(string id, string userId, object claimType, object claimValue)
        {
            if ((claimType == null))
            {
                claimType = System.DBNull.Value;
            }
            if ((claimValue == null))
            {
                claimValue = System.DBNull.Value;
            }
            return await Service.UpdateAsync(id, userId, claimType, claimValue);
        }
        
        public static int Delete(string id)
        {
            return Service.Delete(id);
        }
        
        public static async Task<int> DeleteAsync(string id)
        {
            return await Service.DeleteAsync(id);
        }
        
        public new int Delete()
        {
            return Service.Delete(Id);
        }
        
        public async Task<int> DeleteAsync()
        {
            return await Service.DeleteAsync(Id);
        }
    }
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbManager
{
    using System;
    using System.Runtime.Serialization;
    using System.Data;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using System.Transactions;
    using SoftBand.EntityManager;
    
    
    // Table('AspNetUserTokens')  Service class
    // Do not add or change code here.
    public partial class AspNetUserTokenService : SoftBand.EntityManager.Service
    {
        
        public AspNetUserTokenSet GetAll()
        {
            return ((AspNetUserTokenSet)(this.GetAll("AspNetUserTokens", typeof(AspNetUserTokenSet))));
        }
        
        public string GetAllJson()
        {
            return this.GetAllJson("AspNetUserTokens");
        }
        
        public async Task<AspNetUserTokenSet> GetAllAsync()
        {
            return ((AspNetUserTokenSet)(await this.GetAllAsync("AspNetUserTokens", typeof(AspNetUserTokenSet))));
        }
        
        public async Task<string> GetAllJsonAsync()
        {
            return await this.GetAllJsonAsync("AspNetUserTokens");
        }
        
        public AspNetUserTokenSet GetForAspNetUsers(string userId)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [AspNetUserTokens] WHERE UserId = @userId";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "userId";
            AddParameters(selectCmd, paraNames, userId);
            AspNetUserTokenSet entitySet = ((AspNetUserTokenSet)(this.GetEntitySet(selectCmd, typeof(AspNetUserTokenSet))));
            selectCmd.Dispose();
            return entitySet;
        }
        
        public async Task<AspNetUserTokenSet> GetForAspNetUsersAsync(string userId)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [AspNetUserTokens] WHERE UserId = @userId";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "userId";
            AddParameters(selectCmd, paraNames, userId);
            AspNetUserTokenSet entitySet = ((AspNetUserTokenSet)(await this.GetEntitySetAsync(selectCmd, typeof(AspNetUserTokenSet))));
            selectCmd.Dispose();
            return entitySet;
        }
        
        public string GetForAspNetUsersJson(string userId)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [AspNetUserTokens] WHERE UserId = @userId";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "userId";
            AddParameters(selectCmd, paraNames, userId);
            return  this.GetJsonDataSet(selectCmd);
        }
        
        public async Task<string> GetForAspNetUsersJsonAsync(string userId)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [AspNetUserTokens] WHERE UserId = @userId";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "userId";
            AddParameters(selectCmd, paraNames, userId);
            return await this.GetJsonDataSetAsync(selectCmd);
        }
        
        public AspNetUserToken GetByKey(string id)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM AspNetUserTokens WHERE Id = @id";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "id";
            AddParameters(selectCmd, paraNames, id);
            // 
            AspNetUserToken entity = ((AspNetUserToken)(this.GetEntity(selectCmd, typeof(AspNetUserTokenSet))));
            selectCmd.Dispose();
            return entity;
        }
        
        public  string GetByKeyJson(string id)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM AspNetUserTokens WHERE Id = @id";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "id";
            AddParameters(selectCmd, paraNames, id);
            // 
            return this.GetJsonDataSet(selectCmd);
        }
        
        public async Task<AspNetUserToken> GetByKeyAsync(string id)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM AspNetUserTokens WHERE Id = @id";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "id";
            AddParameters(selectCmd, paraNames, id);
            // 
            // GetByKeyAsync 를 호출한다
            AspNetUserToken entity = ((AspNetUserToken)(await this.GetEntityAsync(selectCmd, typeof(AspNetUserTokenSet))));
            selectCmd.Dispose();
            return entity;
        }
        
        public async Task<string> GetByKeyJsonAsync(string id)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM AspNetUserTokens WHERE Id = @id";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "id";
            AddParameters(selectCmd, paraNames, id);
            // 
            return await this.GetJsonDataSetAsync(selectCmd);
        }
        
        public AspNetUserToken Insert(string id, string userId, object claimType, object claimValue)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand insertCommand = DbCommandFactory.CreateDbCommand();
            insertCommand.CommandText = "INSERT INTO AspNetUserTokens(Id, UserId, ClaimType, ClaimValue) VALUES (@id, @use" +
                "rId, @claimType, @claimValue) ";
            insertCommand.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "id,userId,claimType,claimValue";
            AddParameters(insertCommand, paraNames, id, userId, claimType, claimValue);
            // 
            // Insert 를 호출한다
            this.ExecuteNonQuery(insertCommand);
            AspNetUserToken entity = ((AspNetUserToken)(this.GetByKey(id)));
            insertCommand.Dispose();
            return entity;
        }
        
        public async Task<AspNetUserToken> InsertAsync(string id, string userId, object claimType, object claimValue)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand insertCommand = DbCommandFactory.CreateDbCommand();
            insertCommand.CommandText = "INSERT INTO AspNetUserTokens(Id, UserId, ClaimType, ClaimValue) VALUES (@id, @use" +
                "rId, @claimType, @claimValue) ";
            insertCommand.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "id,userId,claimType,claimValue";
            AddParameters(insertCommand, paraNames, id, userId, claimType, claimValue);
            // 
            // InsertAsync 를 호출한다
            await this.ExecuteNonQueryAsync(insertCommand);
            AspNetUserToken entity = ((AspNetUserToken)(await this.GetByKeyAsync(id)));
            insertCommand.Dispose();
            return entity;
        }
        
        public int Update(string id, string userId, object claimType, object claimValue)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand updateCmd = DbCommandFactory.CreateDbCommand();
            updateCmd.CommandText = "UPDATE AspNetUserTokens SET UserId = @userId, ClaimType = @claimType, ClaimValue " +
                "= @claimValue WHERE Id = @id";
            updateCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "id,userId,claimType,claimValue";
            AddParameters(updateCmd, paraNames, id, userId, claimType, claimValue);
            // 
            // Update 를 호출한다
            int executeCnt = this.ExecuteNonQuery(updateCmd);
            updateCmd.Dispose();
            return executeCnt;
        }
        
        public async Task<int> UpdateAsync(string id, string userId, object claimType, object claimValue)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand updateCmd = DbCommandFactory.CreateDbCommand();
            updateCmd.CommandText = "UPDATE AspNetUserTokens SET UserId = @userId, ClaimType = @claimType, ClaimValue " +
                "= @claimValue WHERE Id = @id";
            updateCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "id,userId,claimType,claimValue";
            AddParameters(updateCmd, paraNames, id, userId, claimType, claimValue);
            // 
            // Update 를 호출한다
            int executeCnt = await this.ExecuteNonQueryAsync(updateCmd);
            updateCmd.Dispose();
            return executeCnt;
        }
        
        public int Delete(string id)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand deleteCmd = DbCommandFactory.CreateDbCommand();
            deleteCmd.CommandText = "DELETE FROM AspNetUserTokens WHERE Id = @id";
            deleteCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "id";
            AddParameters(deleteCmd, paraNames, id);
            // 
            // Delete 를 호출한다
            int executeCnt = this.ExecuteNonQuery(deleteCmd);
            deleteCmd.Dispose();
            return executeCnt;
        }
        
        public async Task<int> DeleteAsync(string id)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand deleteCmd = DbCommandFactory.CreateDbCommand();
            deleteCmd.CommandText = "DELETE FROM AspNetUserTokens WHERE Id = @id";
            deleteCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "id";
            AddParameters(deleteCmd, paraNames, id);
            // 
            // Delete 를 호출한다
            int executeCnt = await this.ExecuteNonQueryAsync(deleteCmd);
            deleteCmd.Dispose();
            return executeCnt;
        }
    }
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbManager
{
    using System;
    using System.Runtime.Serialization;
    using System.Data;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using System.Transactions;
    using SoftBand.EntityManager;
    
    
    // Table('AspNetUserTokens') EntitySet class
    // Do not add or change code here.
    [System.Serializable()]
    public partial class AspNetUserTokenSet : SoftBand.EntityManager.EntitySet, System.Collections.IEnumerable
    {
        
        // Constructor
        public AspNetUserTokenSet() : 
                this(null)
        {
        }
        
        // basic constructor
        protected AspNetUserTokenSet(object state)
        {
            this.Setup();
        }
        
        // remoting constructor...
        protected AspNetUserTokenSet(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context)
        {
            this.Setup();
        }
        
        public AspNetUserTokenBoundCollection Entities
        {
            get
            {
                return this.GetBoundCollection();
            }
        }
        
        // shared object initialization...
        private void Setup()
        {
            this.EntityType = typeof(AspNetUserToken);
        }
        
        private AspNetUserTokenBoundCollection GetBoundCollection()
        {
            return this.GetBoundCollection(0);
        }
        
        private AspNetUserTokenBoundCollection GetBoundCollection(int tableIndex)
        {
            return ((AspNetUserTokenBoundCollection)(this.GetBoundCollection(this, tableIndex, typeof(AspNetUserTokenBoundCollection))));
        }
        
        public partial class AspNetUserTokenBoundCollection : SoftBand.EntityManager.EntityBoundCollection
        {
            
            public new AspNetUserToken this[int index]
            {
                get
                {
                    return ((AspNetUserToken)(this.EntitySet.GetEntity(this.TableIndex, index)));
                }
            }
        }
    }
}
