//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbManager
{
    using System;
    using System.Runtime.Serialization;
    using System.Data;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using System.Transactions;
    using SoftBand.EntityManager;
    
    
    // Table('AspNetUsers') Entity class
    // Do not add or change code here.
    [System.Serializable()]
    public partial class AspNetUser : SoftBand.EntityManager.Entity
    {
        
        public AspNetUser()
        {
            this.DefineColumns(23);
        }
        
        public string Id
        {
            get
            {
                return ((string)(this[0]));
            }
            set
            {
                this[0] = value;
            }
        }
        
        public string UserName
        {
            get
            {
                return ((string)(this[1]));
            }
            set
            {
                this[1] = value;
            }
        }
        
        public string NormalizedUserName
        {
            get
            {
                return ((string)(this[2]));
            }
            set
            {
                this[2] = value;
            }
        }
        
        public string Email
        {
            get
            {
                return ((string)(this.IsnullZeroOrNull(3, typeof(string))));
            }
            set
            {
                this[3] = value;
            }
        }
        
        public string NormalizedEmail
        {
            get
            {
                return ((string)(this.IsnullZeroOrNull(4, typeof(string))));
            }
            set
            {
                this[4] = value;
            }
        }
        
        public bool EmailConfirmed
        {
            get
            {
                return ((bool)(this.IsnullZeroOrNull(5, typeof(bool))));
            }
            set
            {
                this[5] = value;
            }
        }
        
        public string PasswordHash
        {
            get
            {
                return ((string)(this[6]));
            }
            set
            {
                this[6] = value;
            }
        }
        
        public string SecurityStamp
        {
            get
            {
                return ((string)(this.IsnullZeroOrNull(7, typeof(string))));
            }
            set
            {
                this[7] = value;
            }
        }
        
        public string ConcurrencyStamp
        {
            get
            {
                return ((string)(this.IsnullZeroOrNull(8, typeof(string))));
            }
            set
            {
                this[8] = value;
            }
        }
        
        public string PhoneNumber
        {
            get
            {
                return ((string)(this.IsnullZeroOrNull(9, typeof(string))));
            }
            set
            {
                this[9] = value;
            }
        }
        
        public bool PhoneNumberConfirmed
        {
            get
            {
                return ((bool)(this[10]));
            }
            set
            {
                this[10] = value;
            }
        }
        
        public bool TwoFactorEnabled
        {
            get
            {
                return ((bool)(this[11]));
            }
            set
            {
                this[11] = value;
            }
        }
        
        public System.DateTimeOffset LockoutEnd
        {
            get
            {
                return ((System.DateTimeOffset)(this.IsnullZeroOrNull(12, typeof(System.DateTimeOffset))));
            }
            set
            {
                this[12] = value;
            }
        }
        
        public bool LockoutEnabled
        {
            get
            {
                return ((bool)(this[13]));
            }
            set
            {
                this[13] = value;
            }
        }
        
        public int AccessFailedCount
        {
            get
            {
                return ((int)(this[14]));
            }
            set
            {
                this[14] = value;
            }
        }
        
        public string CompanyName
        {
            get
            {
                return ((string)(this.IsnullZeroOrNull(15, typeof(string))));
            }
            set
            {
                this[15] = value;
            }
        }
        
        public string DepartmentName
        {
            get
            {
                return ((string)(this.IsnullZeroOrNull(16, typeof(string))));
            }
            set
            {
                this[16] = value;
            }
        }
        
        public string CustomerClass
        {
            get
            {
                return ((string)(this[17]));
            }
            set
            {
                this[17] = value;
            }
        }
        
        public int CountOfLogins
        {
            get
            {
                return ((int)(this[18]));
            }
            set
            {
                this[18] = value;
            }
        }
        
        public System.DateTime FinalLogin
        {
            get
            {
                return ((System.DateTime)(this.IsnullZeroOrNull(19, typeof(System.DateTime))));
            }
            set
            {
                this[19] = value;
            }
        }
        
        public string SignUpTime
        {
            get
            {
                return ((string)(this.IsnullZeroOrNull(20, typeof(string))));
            }
            set
            {
                this[20] = value;
            }
        }
        
        public string ActivityInformation
        {
            get
            {
                return ((string)(this[21]));
            }
            set
            {
                this[21] = value;
            }
        }
        
        public string DiagnosisEvaluationStatus
        {
            get
            {
                return ((string)(this[22]));
            }
            set
            {
                this[22] = value;
            }
        }
        
        public static AspNetUserService Service
        {
            get
            {
                return ((AspNetUserService)(GetServiceObject(typeof(AspNetUser), typeof(AspNetUserService))));
            }
        }
        
        public bool IsEmailNull()
        {
            return this.IsNull(3);
        }
        
        public void SetEmailToNull()
        {
            this[3] = System.DBNull.Value;
        }
        
        public bool IsNormalizedEmailNull()
        {
            return this.IsNull(4);
        }
        
        public void SetNormalizedEmailToNull()
        {
            this[4] = System.DBNull.Value;
        }
        
        public bool IsEmailConfirmedNull()
        {
            return this.IsNull(5);
        }
        
        public void SetEmailConfirmedToNull()
        {
            this[5] = System.DBNull.Value;
        }
        
        public bool IsSecurityStampNull()
        {
            return this.IsNull(7);
        }
        
        public void SetSecurityStampToNull()
        {
            this[7] = System.DBNull.Value;
        }
        
        public bool IsConcurrencyStampNull()
        {
            return this.IsNull(8);
        }
        
        public void SetConcurrencyStampToNull()
        {
            this[8] = System.DBNull.Value;
        }
        
        public bool IsPhoneNumberNull()
        {
            return this.IsNull(9);
        }
        
        public void SetPhoneNumberToNull()
        {
            this[9] = System.DBNull.Value;
        }
        
        public bool IsLockoutEndNull()
        {
            return this.IsNull(12);
        }
        
        public void SetLockoutEndToNull()
        {
            this[12] = System.DBNull.Value;
        }
        
        public bool IsCompanyNameNull()
        {
            return this.IsNull(15);
        }
        
        public void SetCompanyNameToNull()
        {
            this[15] = System.DBNull.Value;
        }
        
        public bool IsDepartmentNameNull()
        {
            return this.IsNull(16);
        }
        
        public void SetDepartmentNameToNull()
        {
            this[16] = System.DBNull.Value;
        }
        
        public bool IsFinalLoginNull()
        {
            return this.IsNull(19);
        }
        
        public void SetFinalLoginToNull()
        {
            this[19] = System.DBNull.Value;
        }
        
        public bool IsSignUpTimeNull()
        {
            return this.IsNull(20);
        }
        
        public void SetSignUpTimeToNull()
        {
            this[20] = System.DBNull.Value;
        }
        
        public static AspNetUserSet GetAll()
        {
            return Service.GetAll();
        }
        
        public static string GetAllJson()
        {
            return Service.GetAllJson();
        }
        
        public static async Task<AspNetUserSet> GetAllAsync()
        {
            return await Service.GetAllAsync();
        }
        
        public static async Task<string> GetAllJsonAsync()
        {
            return await Service.GetAllJsonAsync();
        }
        
        public static AspNetUser GetByKey(string id)
        {
            return Service.GetByKey(id);
        }
        
        public static string GetByKeyJson(string id)
        {
            return Service.GetByKeyJson(id);
        }
        
        public static async Task<AspNetUser> GetByKeyAsync(string id)
        {
            return await Service.GetByKeyAsync(id);
        }
        
        public static async Task<string> GetByKeyJsonAsync(string id)
        {
            return await Service.GetByKeyJsonAsync(id);
        }
        
        public static AspNetUser Insert(
                    string id, 
                    string userName, 
                    string normalizedUserName, 
                    object email, 
                    object normalizedEmail, 
                    object emailConfirmed, 
                    string passwordHash, 
                    object securityStamp, 
                    object concurrencyStamp, 
                    object phoneNumber, 
                    bool phoneNumberConfirmed, 
                    bool twoFactorEnabled, 
                    object lockoutEnd, 
                    bool lockoutEnabled, 
                    int accessFailedCount, 
                    object companyName, 
                    object departmentName, 
                    string customerClass, 
                    int countOfLogins, 
                    object finalLogin, 
                    object signUpTime, 
                    string activityInformation, 
                    string diagnosisEvaluationStatus)
        {
            // Insert 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            if ((email == null))
            {
                email = System.DBNull.Value;
            }
            if ((normalizedEmail == null))
            {
                normalizedEmail = System.DBNull.Value;
            }
            if ((emailConfirmed == null))
            {
                emailConfirmed = System.DBNull.Value;
            }
            if ((securityStamp == null))
            {
                securityStamp = System.DBNull.Value;
            }
            if ((concurrencyStamp == null))
            {
                concurrencyStamp = System.DBNull.Value;
            }
            if ((phoneNumber == null))
            {
                phoneNumber = System.DBNull.Value;
            }
            if ((lockoutEnd == null))
            {
                lockoutEnd = System.DBNull.Value;
            }
            if ((companyName == null))
            {
                companyName = System.DBNull.Value;
            }
            if ((departmentName == null))
            {
                departmentName = System.DBNull.Value;
            }
            if ((finalLogin == null))
            {
                finalLogin = System.DBNull.Value;
            }
            if ((signUpTime == null))
            {
                signUpTime = System.DBNull.Value;
            }
            return Service.Insert(id, userName, normalizedUserName, email, normalizedEmail, emailConfirmed, passwordHash, securityStamp, concurrencyStamp, phoneNumber, phoneNumberConfirmed, twoFactorEnabled, lockoutEnd, lockoutEnabled, accessFailedCount, companyName, departmentName, customerClass, countOfLogins, finalLogin, signUpTime, activityInformation, diagnosisEvaluationStatus);
        }
        
        public static async Task<AspNetUser> InsertAsync(
                    string id, 
                    string userName, 
                    string normalizedUserName, 
                    object email, 
                    object normalizedEmail, 
                    object emailConfirmed, 
                    string passwordHash, 
                    object securityStamp, 
                    object concurrencyStamp, 
                    object phoneNumber, 
                    bool phoneNumberConfirmed, 
                    bool twoFactorEnabled, 
                    object lockoutEnd, 
                    bool lockoutEnabled, 
                    int accessFailedCount, 
                    object companyName, 
                    object departmentName, 
                    string customerClass, 
                    int countOfLogins, 
                    object finalLogin, 
                    object signUpTime, 
                    string activityInformation, 
                    string diagnosisEvaluationStatus)
        {
            // InsertAsync 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            if ((email == null))
            {
                email = System.DBNull.Value;
            }
            if ((normalizedEmail == null))
            {
                normalizedEmail = System.DBNull.Value;
            }
            if ((emailConfirmed == null))
            {
                emailConfirmed = System.DBNull.Value;
            }
            if ((securityStamp == null))
            {
                securityStamp = System.DBNull.Value;
            }
            if ((concurrencyStamp == null))
            {
                concurrencyStamp = System.DBNull.Value;
            }
            if ((phoneNumber == null))
            {
                phoneNumber = System.DBNull.Value;
            }
            if ((lockoutEnd == null))
            {
                lockoutEnd = System.DBNull.Value;
            }
            if ((companyName == null))
            {
                companyName = System.DBNull.Value;
            }
            if ((departmentName == null))
            {
                departmentName = System.DBNull.Value;
            }
            if ((finalLogin == null))
            {
                finalLogin = System.DBNull.Value;
            }
            if ((signUpTime == null))
            {
                signUpTime = System.DBNull.Value;
            }
            return await Service.InsertAsync(id, userName, normalizedUserName, email, normalizedEmail, emailConfirmed, passwordHash, securityStamp, concurrencyStamp, phoneNumber, phoneNumberConfirmed, twoFactorEnabled, lockoutEnd, lockoutEnabled, accessFailedCount, companyName, departmentName, customerClass, countOfLogins, finalLogin, signUpTime, activityInformation, diagnosisEvaluationStatus);
        }
        
        public new AspNetUser Insert()
        {
            // Insert 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            return Insert(Id, UserName, NormalizedUserName, Email, NormalizedEmail, EmailConfirmed, PasswordHash, SecurityStamp, ConcurrencyStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEnd, LockoutEnabled, AccessFailedCount, CompanyName, DepartmentName, CustomerClass, CountOfLogins, FinalLogin, SignUpTime, ActivityInformation, DiagnosisEvaluationStatus);
        }
        
        public async Task<AspNetUser> InsertAsync()
        {
            // Insert 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            return await InsertAsync(Id, UserName, NormalizedUserName, Email, NormalizedEmail, EmailConfirmed, PasswordHash, SecurityStamp, ConcurrencyStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEnd, LockoutEnabled, AccessFailedCount, CompanyName, DepartmentName, CustomerClass, CountOfLogins, FinalLogin, SignUpTime, ActivityInformation, DiagnosisEvaluationStatus);
        }
        
        public new int Update()
        {
            // 인수를 해당 파라메타에 옮긴다
            string idParam = this.Id;
            string userNameParam = this.UserName;
            string normalizedUserNameParam = this.NormalizedUserName;
            object emailParam;
            if ((this.IsEmailNull() == false))
            {
                emailParam = this.Email;
            }
            else
            {
                emailParam = System.DBNull.Value;
            }
            object normalizedEmailParam;
            if ((this.IsNormalizedEmailNull() == false))
            {
                normalizedEmailParam = this.NormalizedEmail;
            }
            else
            {
                normalizedEmailParam = System.DBNull.Value;
            }
            object emailConfirmedParam;
            if ((this.IsEmailConfirmedNull() == false))
            {
                emailConfirmedParam = this.EmailConfirmed;
            }
            else
            {
                emailConfirmedParam = System.DBNull.Value;
            }
            string passwordHashParam = this.PasswordHash;
            object securityStampParam;
            if ((this.IsSecurityStampNull() == false))
            {
                securityStampParam = this.SecurityStamp;
            }
            else
            {
                securityStampParam = System.DBNull.Value;
            }
            object concurrencyStampParam;
            if ((this.IsConcurrencyStampNull() == false))
            {
                concurrencyStampParam = this.ConcurrencyStamp;
            }
            else
            {
                concurrencyStampParam = System.DBNull.Value;
            }
            object phoneNumberParam;
            if ((this.IsPhoneNumberNull() == false))
            {
                phoneNumberParam = this.PhoneNumber;
            }
            else
            {
                phoneNumberParam = System.DBNull.Value;
            }
            bool phoneNumberConfirmedParam = this.PhoneNumberConfirmed;
            bool twoFactorEnabledParam = this.TwoFactorEnabled;
            object lockoutEndParam;
            if ((this.IsLockoutEndNull() == false))
            {
                lockoutEndParam = this.LockoutEnd;
            }
            else
            {
                lockoutEndParam = System.DBNull.Value;
            }
            bool lockoutEnabledParam = this.LockoutEnabled;
            int accessFailedCountParam = this.AccessFailedCount;
            object companyNameParam;
            if ((this.IsCompanyNameNull() == false))
            {
                companyNameParam = this.CompanyName;
            }
            else
            {
                companyNameParam = System.DBNull.Value;
            }
            object departmentNameParam;
            if ((this.IsDepartmentNameNull() == false))
            {
                departmentNameParam = this.DepartmentName;
            }
            else
            {
                departmentNameParam = System.DBNull.Value;
            }
            string customerClassParam = this.CustomerClass;
            int countOfLoginsParam = this.CountOfLogins;
            object finalLoginParam;
            if ((this.IsFinalLoginNull() == false))
            {
                finalLoginParam = this.FinalLogin;
            }
            else
            {
                finalLoginParam = System.DBNull.Value;
            }
            object signUpTimeParam;
            if ((this.IsSignUpTimeNull() == false))
            {
                signUpTimeParam = this.SignUpTime;
            }
            else
            {
                signUpTimeParam = System.DBNull.Value;
            }
            string activityInformationParam = this.ActivityInformation;
            string diagnosisEvaluationStatusParam = this.DiagnosisEvaluationStatus;
            // update 실행
            return Service.Update(idParam, userNameParam, normalizedUserNameParam, emailParam, normalizedEmailParam, emailConfirmedParam, passwordHashParam, securityStampParam, concurrencyStampParam, phoneNumberParam, phoneNumberConfirmedParam, twoFactorEnabledParam, lockoutEndParam, lockoutEnabledParam, accessFailedCountParam, companyNameParam, departmentNameParam, customerClassParam, countOfLoginsParam, finalLoginParam, signUpTimeParam, activityInformationParam, diagnosisEvaluationStatusParam);
        }
        
        public async Task<int> UpdateAsync()
        {
            // 인수를 해당 파라메타에 옮긴다
            string idParam = this.Id;
            string userNameParam = this.UserName;
            string normalizedUserNameParam = this.NormalizedUserName;
            object emailParam;
            if ((this.IsEmailNull() == false))
            {
                emailParam = this.Email;
            }
            else
            {
                emailParam = System.DBNull.Value;
            }
            object normalizedEmailParam;
            if ((this.IsNormalizedEmailNull() == false))
            {
                normalizedEmailParam = this.NormalizedEmail;
            }
            else
            {
                normalizedEmailParam = System.DBNull.Value;
            }
            object emailConfirmedParam;
            if ((this.IsEmailConfirmedNull() == false))
            {
                emailConfirmedParam = this.EmailConfirmed;
            }
            else
            {
                emailConfirmedParam = System.DBNull.Value;
            }
            string passwordHashParam = this.PasswordHash;
            object securityStampParam;
            if ((this.IsSecurityStampNull() == false))
            {
                securityStampParam = this.SecurityStamp;
            }
            else
            {
                securityStampParam = System.DBNull.Value;
            }
            object concurrencyStampParam;
            if ((this.IsConcurrencyStampNull() == false))
            {
                concurrencyStampParam = this.ConcurrencyStamp;
            }
            else
            {
                concurrencyStampParam = System.DBNull.Value;
            }
            object phoneNumberParam;
            if ((this.IsPhoneNumberNull() == false))
            {
                phoneNumberParam = this.PhoneNumber;
            }
            else
            {
                phoneNumberParam = System.DBNull.Value;
            }
            bool phoneNumberConfirmedParam = this.PhoneNumberConfirmed;
            bool twoFactorEnabledParam = this.TwoFactorEnabled;
            object lockoutEndParam;
            if ((this.IsLockoutEndNull() == false))
            {
                lockoutEndParam = this.LockoutEnd;
            }
            else
            {
                lockoutEndParam = System.DBNull.Value;
            }
            bool lockoutEnabledParam = this.LockoutEnabled;
            int accessFailedCountParam = this.AccessFailedCount;
            object companyNameParam;
            if ((this.IsCompanyNameNull() == false))
            {
                companyNameParam = this.CompanyName;
            }
            else
            {
                companyNameParam = System.DBNull.Value;
            }
            object departmentNameParam;
            if ((this.IsDepartmentNameNull() == false))
            {
                departmentNameParam = this.DepartmentName;
            }
            else
            {
                departmentNameParam = System.DBNull.Value;
            }
            string customerClassParam = this.CustomerClass;
            int countOfLoginsParam = this.CountOfLogins;
            object finalLoginParam;
            if ((this.IsFinalLoginNull() == false))
            {
                finalLoginParam = this.FinalLogin;
            }
            else
            {
                finalLoginParam = System.DBNull.Value;
            }
            object signUpTimeParam;
            if ((this.IsSignUpTimeNull() == false))
            {
                signUpTimeParam = this.SignUpTime;
            }
            else
            {
                signUpTimeParam = System.DBNull.Value;
            }
            string activityInformationParam = this.ActivityInformation;
            string diagnosisEvaluationStatusParam = this.DiagnosisEvaluationStatus;
            return await Service.UpdateAsync(idParam, userNameParam, normalizedUserNameParam, emailParam, normalizedEmailParam, emailConfirmedParam, passwordHashParam, securityStampParam, concurrencyStampParam, phoneNumberParam, phoneNumberConfirmedParam, twoFactorEnabledParam, lockoutEndParam, lockoutEnabledParam, accessFailedCountParam, companyNameParam, departmentNameParam, customerClassParam, countOfLoginsParam, finalLoginParam, signUpTimeParam, activityInformationParam, diagnosisEvaluationStatusParam);
        }
        
        public static int Update(
                    string id, 
                    string userName, 
                    string normalizedUserName, 
                    object email, 
                    object normalizedEmail, 
                    object emailConfirmed, 
                    string passwordHash, 
                    object securityStamp, 
                    object concurrencyStamp, 
                    object phoneNumber, 
                    bool phoneNumberConfirmed, 
                    bool twoFactorEnabled, 
                    object lockoutEnd, 
                    bool lockoutEnabled, 
                    int accessFailedCount, 
                    object companyName, 
                    object departmentName, 
                    string customerClass, 
                    int countOfLogins, 
                    object finalLogin, 
                    object signUpTime, 
                    string activityInformation, 
                    string diagnosisEvaluationStatus)
        {
            if ((email == null))
            {
                email = System.DBNull.Value;
            }
            if ((normalizedEmail == null))
            {
                normalizedEmail = System.DBNull.Value;
            }
            if ((emailConfirmed == null))
            {
                emailConfirmed = System.DBNull.Value;
            }
            if ((securityStamp == null))
            {
                securityStamp = System.DBNull.Value;
            }
            if ((concurrencyStamp == null))
            {
                concurrencyStamp = System.DBNull.Value;
            }
            if ((phoneNumber == null))
            {
                phoneNumber = System.DBNull.Value;
            }
            if ((lockoutEnd == null))
            {
                lockoutEnd = System.DBNull.Value;
            }
            if ((companyName == null))
            {
                companyName = System.DBNull.Value;
            }
            if ((departmentName == null))
            {
                departmentName = System.DBNull.Value;
            }
            if ((finalLogin == null))
            {
                finalLogin = System.DBNull.Value;
            }
            if ((signUpTime == null))
            {
                signUpTime = System.DBNull.Value;
            }
            return Service.Update(id, userName, normalizedUserName, email, normalizedEmail, emailConfirmed, passwordHash, securityStamp, concurrencyStamp, phoneNumber, phoneNumberConfirmed, twoFactorEnabled, lockoutEnd, lockoutEnabled, accessFailedCount, companyName, departmentName, customerClass, countOfLogins, finalLogin, signUpTime, activityInformation, diagnosisEvaluationStatus);
        }
        
        public static async Task<int> UpdateAsync(
                    string id, 
                    string userName, 
                    string normalizedUserName, 
                    object email, 
                    object normalizedEmail, 
                    object emailConfirmed, 
                    string passwordHash, 
                    object securityStamp, 
                    object concurrencyStamp, 
                    object phoneNumber, 
                    bool phoneNumberConfirmed, 
                    bool twoFactorEnabled, 
                    object lockoutEnd, 
                    bool lockoutEnabled, 
                    int accessFailedCount, 
                    object companyName, 
                    object departmentName, 
                    string customerClass, 
                    int countOfLogins, 
                    object finalLogin, 
                    object signUpTime, 
                    string activityInformation, 
                    string diagnosisEvaluationStatus)
        {
            if ((email == null))
            {
                email = System.DBNull.Value;
            }
            if ((normalizedEmail == null))
            {
                normalizedEmail = System.DBNull.Value;
            }
            if ((emailConfirmed == null))
            {
                emailConfirmed = System.DBNull.Value;
            }
            if ((securityStamp == null))
            {
                securityStamp = System.DBNull.Value;
            }
            if ((concurrencyStamp == null))
            {
                concurrencyStamp = System.DBNull.Value;
            }
            if ((phoneNumber == null))
            {
                phoneNumber = System.DBNull.Value;
            }
            if ((lockoutEnd == null))
            {
                lockoutEnd = System.DBNull.Value;
            }
            if ((companyName == null))
            {
                companyName = System.DBNull.Value;
            }
            if ((departmentName == null))
            {
                departmentName = System.DBNull.Value;
            }
            if ((finalLogin == null))
            {
                finalLogin = System.DBNull.Value;
            }
            if ((signUpTime == null))
            {
                signUpTime = System.DBNull.Value;
            }
            return await Service.UpdateAsync(id, userName, normalizedUserName, email, normalizedEmail, emailConfirmed, passwordHash, securityStamp, concurrencyStamp, phoneNumber, phoneNumberConfirmed, twoFactorEnabled, lockoutEnd, lockoutEnabled, accessFailedCount, companyName, departmentName, customerClass, countOfLogins, finalLogin, signUpTime, activityInformation, diagnosisEvaluationStatus);
        }
        
        public static int Delete(string id)
        {
            return Service.Delete(id);
        }
        
        public static async Task<int> DeleteAsync(string id)
        {
            return await Service.DeleteAsync(id);
        }
        
        public new int Delete()
        {
            return Service.Delete(Id);
        }
        
        public async Task<int> DeleteAsync()
        {
            return await Service.DeleteAsync(Id);
        }
    }
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbManager
{
    using System;
    using System.Runtime.Serialization;
    using System.Data;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using System.Transactions;
    using SoftBand.EntityManager;
    
    
    // Table('AspNetUsers')  Service class
    // Do not add or change code here.
    public partial class AspNetUserService : SoftBand.EntityManager.Service
    {
        
        public AspNetUserSet GetAll()
        {
            return ((AspNetUserSet)(this.GetAll("AspNetUsers", typeof(AspNetUserSet))));
        }
        
        public string GetAllJson()
        {
            return this.GetAllJson("AspNetUsers");
        }
        
        public async Task<AspNetUserSet> GetAllAsync()
        {
            return ((AspNetUserSet)(await this.GetAllAsync("AspNetUsers", typeof(AspNetUserSet))));
        }
        
        public async Task<string> GetAllJsonAsync()
        {
            return await this.GetAllJsonAsync("AspNetUsers");
        }
        
        public AspNetUser GetByKey(string id)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM AspNetUsers WHERE Id = @id";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "id";
            AddParameters(selectCmd, paraNames, id);
            // 
            AspNetUser entity = ((AspNetUser)(this.GetEntity(selectCmd, typeof(AspNetUserSet))));
            selectCmd.Dispose();
            return entity;
        }
        
        public  string GetByKeyJson(string id)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM AspNetUsers WHERE Id = @id";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "id";
            AddParameters(selectCmd, paraNames, id);
            // 
            return this.GetJsonDataSet(selectCmd);
        }
        
        public async Task<AspNetUser> GetByKeyAsync(string id)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM AspNetUsers WHERE Id = @id";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "id";
            AddParameters(selectCmd, paraNames, id);
            // 
            // GetByKeyAsync 를 호출한다
            AspNetUser entity = ((AspNetUser)(await this.GetEntityAsync(selectCmd, typeof(AspNetUserSet))));
            selectCmd.Dispose();
            return entity;
        }
        
        public async Task<string> GetByKeyJsonAsync(string id)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM AspNetUsers WHERE Id = @id";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "id";
            AddParameters(selectCmd, paraNames, id);
            // 
            return await this.GetJsonDataSetAsync(selectCmd);
        }
        
        public AspNetUser Insert(
                    string id, 
                    string userName, 
                    string normalizedUserName, 
                    object email, 
                    object normalizedEmail, 
                    object emailConfirmed, 
                    string passwordHash, 
                    object securityStamp, 
                    object concurrencyStamp, 
                    object phoneNumber, 
                    bool phoneNumberConfirmed, 
                    bool twoFactorEnabled, 
                    object lockoutEnd, 
                    bool lockoutEnabled, 
                    int accessFailedCount, 
                    object companyName, 
                    object departmentName, 
                    string customerClass, 
                    int countOfLogins, 
                    object finalLogin, 
                    object signUpTime, 
                    string activityInformation, 
                    string diagnosisEvaluationStatus)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand insertCommand = DbCommandFactory.CreateDbCommand();
            insertCommand.CommandText = @"INSERT INTO AspNetUsers(Id, UserName, NormalizedUserName, Email, NormalizedEmail, EmailConfirmed, PasswordHash, SecurityStamp, ConcurrencyStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEnd, LockoutEnabled, AccessFailedCount, CompanyName, DepartmentName, CustomerClass, CountOfLogins, FinalLogin, SignUpTime, ActivityInformation, DiagnosisEvaluationStatus) VALUES (@id, @userName, @normalizedUserName, @email, @normalizedEmail, @emailConfirmed, @passwordHash, @securityStamp, @concurrencyStamp, @phoneNumber, @phoneNumberConfirmed, @twoFactorEnabled, @lockoutEnd, @lockoutEnabled, @accessFailedCount, @companyName, @departmentName, @customerClass, @countOfLogins, @finalLogin, @signUpTime, @activityInformation, @diagnosisEvaluationStatus) ";
            insertCommand.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = @"id,userName,normalizedUserName,email,normalizedEmail,emailConfirmed,passwordHash,securityStamp,concurrencyStamp,phoneNumber,phoneNumberConfirmed,twoFactorEnabled,lockoutEnd,lockoutEnabled,accessFailedCount,companyName,departmentName,customerClass,countOfLogins,finalLogin,signUpTime,activityInformation,diagnosisEvaluationStatus";
            AddParameters(insertCommand, paraNames, id, userName, normalizedUserName, email, normalizedEmail, emailConfirmed, passwordHash, securityStamp, concurrencyStamp, phoneNumber, phoneNumberConfirmed, twoFactorEnabled, lockoutEnd, lockoutEnabled, accessFailedCount, companyName, departmentName, customerClass, countOfLogins, finalLogin, signUpTime, activityInformation, diagnosisEvaluationStatus);
            // 
            // Insert 를 호출한다
            this.ExecuteNonQuery(insertCommand);
            AspNetUser entity = ((AspNetUser)(this.GetByKey(id)));
            insertCommand.Dispose();
            return entity;
        }
        
        public async Task<AspNetUser> InsertAsync(
                    string id, 
                    string userName, 
                    string normalizedUserName, 
                    object email, 
                    object normalizedEmail, 
                    object emailConfirmed, 
                    string passwordHash, 
                    object securityStamp, 
                    object concurrencyStamp, 
                    object phoneNumber, 
                    bool phoneNumberConfirmed, 
                    bool twoFactorEnabled, 
                    object lockoutEnd, 
                    bool lockoutEnabled, 
                    int accessFailedCount, 
                    object companyName, 
                    object departmentName, 
                    string customerClass, 
                    int countOfLogins, 
                    object finalLogin, 
                    object signUpTime, 
                    string activityInformation, 
                    string diagnosisEvaluationStatus)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand insertCommand = DbCommandFactory.CreateDbCommand();
            insertCommand.CommandText = @"INSERT INTO AspNetUsers(Id, UserName, NormalizedUserName, Email, NormalizedEmail, EmailConfirmed, PasswordHash, SecurityStamp, ConcurrencyStamp, PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEnd, LockoutEnabled, AccessFailedCount, CompanyName, DepartmentName, CustomerClass, CountOfLogins, FinalLogin, SignUpTime, ActivityInformation, DiagnosisEvaluationStatus) VALUES (@id, @userName, @normalizedUserName, @email, @normalizedEmail, @emailConfirmed, @passwordHash, @securityStamp, @concurrencyStamp, @phoneNumber, @phoneNumberConfirmed, @twoFactorEnabled, @lockoutEnd, @lockoutEnabled, @accessFailedCount, @companyName, @departmentName, @customerClass, @countOfLogins, @finalLogin, @signUpTime, @activityInformation, @diagnosisEvaluationStatus) ";
            insertCommand.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = @"id,userName,normalizedUserName,email,normalizedEmail,emailConfirmed,passwordHash,securityStamp,concurrencyStamp,phoneNumber,phoneNumberConfirmed,twoFactorEnabled,lockoutEnd,lockoutEnabled,accessFailedCount,companyName,departmentName,customerClass,countOfLogins,finalLogin,signUpTime,activityInformation,diagnosisEvaluationStatus";
            AddParameters(insertCommand, paraNames, id, userName, normalizedUserName, email, normalizedEmail, emailConfirmed, passwordHash, securityStamp, concurrencyStamp, phoneNumber, phoneNumberConfirmed, twoFactorEnabled, lockoutEnd, lockoutEnabled, accessFailedCount, companyName, departmentName, customerClass, countOfLogins, finalLogin, signUpTime, activityInformation, diagnosisEvaluationStatus);
            // 
            // InsertAsync 를 호출한다
            await this.ExecuteNonQueryAsync(insertCommand);
            AspNetUser entity = ((AspNetUser)(await this.GetByKeyAsync(id)));
            insertCommand.Dispose();
            return entity;
        }
        
        public int Update(
                    string id, 
                    string userName, 
                    string normalizedUserName, 
                    object email, 
                    object normalizedEmail, 
                    object emailConfirmed, 
                    string passwordHash, 
                    object securityStamp, 
                    object concurrencyStamp, 
                    object phoneNumber, 
                    bool phoneNumberConfirmed, 
                    bool twoFactorEnabled, 
                    object lockoutEnd, 
                    bool lockoutEnabled, 
                    int accessFailedCount, 
                    object companyName, 
                    object departmentName, 
                    string customerClass, 
                    int countOfLogins, 
                    object finalLogin, 
                    object signUpTime, 
                    string activityInformation, 
                    string diagnosisEvaluationStatus)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand updateCmd = DbCommandFactory.CreateDbCommand();
            updateCmd.CommandText = @"UPDATE AspNetUsers SET UserName = @userName, NormalizedUserName = @normalizedUserName, Email = @email, NormalizedEmail = @normalizedEmail, EmailConfirmed = @emailConfirmed, PasswordHash = @passwordHash, SecurityStamp = @securityStamp, ConcurrencyStamp = @concurrencyStamp, PhoneNumber = @phoneNumber, PhoneNumberConfirmed = @phoneNumberConfirmed, TwoFactorEnabled = @twoFactorEnabled, LockoutEnd = @lockoutEnd, LockoutEnabled = @lockoutEnabled, AccessFailedCount = @accessFailedCount, CompanyName = @companyName, DepartmentName = @departmentName, CustomerClass = @customerClass, CountOfLogins = @countOfLogins, FinalLogin = @finalLogin, SignUpTime = @signUpTime, ActivityInformation = @activityInformation, DiagnosisEvaluationStatus = @diagnosisEvaluationStatus WHERE Id = @id";
            updateCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = @"id,userName,normalizedUserName,email,normalizedEmail,emailConfirmed,passwordHash,securityStamp,concurrencyStamp,phoneNumber,phoneNumberConfirmed,twoFactorEnabled,lockoutEnd,lockoutEnabled,accessFailedCount,companyName,departmentName,customerClass,countOfLogins,finalLogin,signUpTime,activityInformation,diagnosisEvaluationStatus";
            AddParameters(updateCmd, paraNames, id, userName, normalizedUserName, email, normalizedEmail, emailConfirmed, passwordHash, securityStamp, concurrencyStamp, phoneNumber, phoneNumberConfirmed, twoFactorEnabled, lockoutEnd, lockoutEnabled, accessFailedCount, companyName, departmentName, customerClass, countOfLogins, finalLogin, signUpTime, activityInformation, diagnosisEvaluationStatus);
            // 
            // Update 를 호출한다
            int executeCnt = this.ExecuteNonQuery(updateCmd);
            updateCmd.Dispose();
            return executeCnt;
        }
        
        public async Task<int> UpdateAsync(
                    string id, 
                    string userName, 
                    string normalizedUserName, 
                    object email, 
                    object normalizedEmail, 
                    object emailConfirmed, 
                    string passwordHash, 
                    object securityStamp, 
                    object concurrencyStamp, 
                    object phoneNumber, 
                    bool phoneNumberConfirmed, 
                    bool twoFactorEnabled, 
                    object lockoutEnd, 
                    bool lockoutEnabled, 
                    int accessFailedCount, 
                    object companyName, 
                    object departmentName, 
                    string customerClass, 
                    int countOfLogins, 
                    object finalLogin, 
                    object signUpTime, 
                    string activityInformation, 
                    string diagnosisEvaluationStatus)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand updateCmd = DbCommandFactory.CreateDbCommand();
            updateCmd.CommandText = @"UPDATE AspNetUsers SET UserName = @userName, NormalizedUserName = @normalizedUserName, Email = @email, NormalizedEmail = @normalizedEmail, EmailConfirmed = @emailConfirmed, PasswordHash = @passwordHash, SecurityStamp = @securityStamp, ConcurrencyStamp = @concurrencyStamp, PhoneNumber = @phoneNumber, PhoneNumberConfirmed = @phoneNumberConfirmed, TwoFactorEnabled = @twoFactorEnabled, LockoutEnd = @lockoutEnd, LockoutEnabled = @lockoutEnabled, AccessFailedCount = @accessFailedCount, CompanyName = @companyName, DepartmentName = @departmentName, CustomerClass = @customerClass, CountOfLogins = @countOfLogins, FinalLogin = @finalLogin, SignUpTime = @signUpTime, ActivityInformation = @activityInformation, DiagnosisEvaluationStatus = @diagnosisEvaluationStatus WHERE Id = @id";
            updateCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = @"id,userName,normalizedUserName,email,normalizedEmail,emailConfirmed,passwordHash,securityStamp,concurrencyStamp,phoneNumber,phoneNumberConfirmed,twoFactorEnabled,lockoutEnd,lockoutEnabled,accessFailedCount,companyName,departmentName,customerClass,countOfLogins,finalLogin,signUpTime,activityInformation,diagnosisEvaluationStatus";
            AddParameters(updateCmd, paraNames, id, userName, normalizedUserName, email, normalizedEmail, emailConfirmed, passwordHash, securityStamp, concurrencyStamp, phoneNumber, phoneNumberConfirmed, twoFactorEnabled, lockoutEnd, lockoutEnabled, accessFailedCount, companyName, departmentName, customerClass, countOfLogins, finalLogin, signUpTime, activityInformation, diagnosisEvaluationStatus);
            // 
            // Update 를 호출한다
            int executeCnt = await this.ExecuteNonQueryAsync(updateCmd);
            updateCmd.Dispose();
            return executeCnt;
        }
        
        public int Delete(string id)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand deleteCmd = DbCommandFactory.CreateDbCommand();
            deleteCmd.CommandText = "DELETE FROM AspNetUsers WHERE Id = @id";
            deleteCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "id";
            AddParameters(deleteCmd, paraNames, id);
            // 
            // Delete 를 호출한다
            int executeCnt = this.ExecuteNonQuery(deleteCmd);
            deleteCmd.Dispose();
            return executeCnt;
        }
        
        public async Task<int> DeleteAsync(string id)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand deleteCmd = DbCommandFactory.CreateDbCommand();
            deleteCmd.CommandText = "DELETE FROM AspNetUsers WHERE Id = @id";
            deleteCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "id";
            AddParameters(deleteCmd, paraNames, id);
            // 
            // Delete 를 호출한다
            int executeCnt = await this.ExecuteNonQueryAsync(deleteCmd);
            deleteCmd.Dispose();
            return executeCnt;
        }
    }
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbManager
{
    using System;
    using System.Runtime.Serialization;
    using System.Data;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using System.Transactions;
    using SoftBand.EntityManager;
    
    
    // Table('AspNetUsers') EntitySet class
    // Do not add or change code here.
    [System.Serializable()]
    public partial class AspNetUserSet : SoftBand.EntityManager.EntitySet, System.Collections.IEnumerable
    {
        
        // Constructor
        public AspNetUserSet() : 
                this(null)
        {
        }
        
        // basic constructor
        protected AspNetUserSet(object state)
        {
            this.Setup();
        }
        
        // remoting constructor...
        protected AspNetUserSet(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context)
        {
            this.Setup();
        }
        
        public AspNetUserBoundCollection Entities
        {
            get
            {
                return this.GetBoundCollection();
            }
        }
        
        // shared object initialization...
        private void Setup()
        {
            this.EntityType = typeof(AspNetUser);
        }
        
        private AspNetUserBoundCollection GetBoundCollection()
        {
            return this.GetBoundCollection(0);
        }
        
        private AspNetUserBoundCollection GetBoundCollection(int tableIndex)
        {
            return ((AspNetUserBoundCollection)(this.GetBoundCollection(this, tableIndex, typeof(AspNetUserBoundCollection))));
        }
        
        public partial class AspNetUserBoundCollection : SoftBand.EntityManager.EntityBoundCollection
        {
            
            public new AspNetUser this[int index]
            {
                get
                {
                    return ((AspNetUser)(this.EntitySet.GetEntity(this.TableIndex, index)));
                }
            }
        }
    }
}
