//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbManager
{
    using System;
    using System.Runtime.Serialization;
    using System.Data;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using System.Transactions;
    using SoftBand.EntityManager;
    
    
    // Table('DiagnosisEvaluationAnswer') Entity class
    // Do not add or change code here.
    [System.Serializable()]
    public partial class DiagnosisEvaluationAnswer : SoftBand.EntityManager.Entity
    {
        
        public DiagnosisEvaluationAnswer()
        {
            this.DefineColumns(15);
        }
        
        public int EvaluationAnswerNumber
        {
            get
            {
                return ((int)(this[0]));
            }
            set
            {
                this[0] = value;
            }
        }
        
        public int AreaNumber
        {
            get
            {
                return ((int)(this[1]));
            }
            set
            {
                this[1] = value;
            }
        }
        
        public int EvaluationQuestionNumber
        {
            get
            {
                return ((int)(this[2]));
            }
            set
            {
                this[2] = value;
            }
        }
        
        public int EvaluationPassageNumber
        {
            get
            {
                return ((int)(this[3]));
            }
            set
            {
                this[3] = value;
            }
        }
        
        public string UserId
        {
            get
            {
                return ((string)(this[4]));
            }
            set
            {
                this[4] = value;
            }
        }
        
        public int DiagnosisLevelNumber
        {
            get
            {
                return ((int)(this[5]));
            }
            set
            {
                this[5] = value;
            }
        }
        
        public string BusinessAnswer
        {
            get
            {
                return ((string)(this[6]));
            }
            set
            {
                this[6] = value;
            }
        }
        
        public int Evidence
        {
            get
            {
                return ((int)(this[7]));
            }
            set
            {
                this[7] = value;
            }
        }
        
        public string DiagEvaluationAnswer
        {
            get
            {
                return ((string)(this.IsnullZeroOrNull(8, typeof(string))));
            }
            set
            {
                this[8] = value;
            }
        }
        
        public System.DateTime DiagnosisDate
        {
            get
            {
                return ((System.DateTime)(this.IsnullZeroOrNull(9, typeof(System.DateTime))));
            }
            set
            {
                this[9] = value;
            }
        }
        
        public string EvaluationAnswer
        {
            get
            {
                return ((string)(this[10]));
            }
            set
            {
                this[10] = value;
            }
        }
        
        public System.DateTime DiagnosisEvaluationData
        {
            get
            {
                return ((System.DateTime)(this[11]));
            }
            set
            {
                this[11] = value;
            }
        }
        
        public string InputStatus
        {
            get
            {
                return ((string)(this[12]));
            }
            set
            {
                this[12] = value;
            }
        }
        
        public string EvaluationStatus
        {
            get
            {
                return ((string)(this[13]));
            }
            set
            {
                this[13] = value;
            }
        }
        
        public string EvaluationResults
        {
            get
            {
                return ((string)(this[14]));
            }
            set
            {
                this[14] = value;
            }
        }
        
        public static DiagnosisEvaluationAnswerService Service
        {
            get
            {
                return ((DiagnosisEvaluationAnswerService)(GetServiceObject(typeof(DiagnosisEvaluationAnswer), typeof(DiagnosisEvaluationAnswerService))));
            }
        }
        
        public bool IsDiagEvaluationAnswerNull()
        {
            return this.IsNull(8);
        }
        
        public void SetDiagEvaluationAnswerToNull()
        {
            this[8] = System.DBNull.Value;
        }
        
        public bool IsDiagnosisDateNull()
        {
            return this.IsNull(9);
        }
        
        public void SetDiagnosisDateToNull()
        {
            this[9] = System.DBNull.Value;
        }
        
        public static DiagnosisEvaluationAnswerSet GetAll()
        {
            return Service.GetAll();
        }
        
        public static string GetAllJson()
        {
            return Service.GetAllJson();
        }
        
        public static async Task<DiagnosisEvaluationAnswerSet> GetAllAsync()
        {
            return await Service.GetAllAsync();
        }
        
        public static async Task<string> GetAllJsonAsync()
        {
            return await Service.GetAllJsonAsync();
        }
        
        public static DiagnosisEvaluationAnswerSet GetForEvaluationAreaNumber(int areaNumber)
        {
            return Service.GetForEvaluationAreaNumber(areaNumber);
        }
        
        public static DiagnosisEvaluationAnswerSet GetForEvaluationQuestion(int evaluationQuestionNumber)
        {
            return Service.GetForEvaluationQuestion(evaluationQuestionNumber);
        }
        
        public static DiagnosisEvaluationAnswerSet GetForEvaluationPassage(int evaluationPassageNumber)
        {
            return Service.GetForEvaluationPassage(evaluationPassageNumber);
        }
        
        public static DiagnosisEvaluationAnswerSet GetForAspNetUsers(string userId)
        {
            return Service.GetForAspNetUsers(userId);
        }
        
        public static DiagnosisEvaluationAnswerSet GetForDiagnosisLevel(int diagnosisLevelNumber)
        {
            return Service.GetForDiagnosisLevel(diagnosisLevelNumber);
        }
        
        public static async Task<DiagnosisEvaluationAnswerSet> GetForEvaluationAreaNumberAsync(int areaNumber)
        {
            return await Service.GetForEvaluationAreaNumberAsync(areaNumber);
        }
        
        public static async Task<DiagnosisEvaluationAnswerSet> GetForEvaluationQuestionAsync(int evaluationQuestionNumber)
        {
            return await Service.GetForEvaluationQuestionAsync(evaluationQuestionNumber);
        }
        
        public static async Task<DiagnosisEvaluationAnswerSet> GetForEvaluationPassageAsync(int evaluationPassageNumber)
        {
            return await Service.GetForEvaluationPassageAsync(evaluationPassageNumber);
        }
        
        public static async Task<DiagnosisEvaluationAnswerSet> GetForAspNetUsersAsync(string userId)
        {
            return await Service.GetForAspNetUsersAsync(userId);
        }
        
        public static async Task<DiagnosisEvaluationAnswerSet> GetForDiagnosisLevelAsync(int diagnosisLevelNumber)
        {
            return await Service.GetForDiagnosisLevelAsync(diagnosisLevelNumber);
        }
        
        public static string GetForEvaluationAreaNumberJson(int areaNumber)
        {
            return Service.GetForEvaluationAreaNumberJson(areaNumber);
        }
        
        public static string GetForEvaluationQuestionJson(int evaluationQuestionNumber)
        {
            return Service.GetForEvaluationQuestionJson(evaluationQuestionNumber);
        }
        
        public static string GetForEvaluationPassageJson(int evaluationPassageNumber)
        {
            return Service.GetForEvaluationPassageJson(evaluationPassageNumber);
        }
        
        public static string GetForAspNetUsersJson(string userId)
        {
            return Service.GetForAspNetUsersJson(userId);
        }
        
        public static string GetForDiagnosisLevelJson(int diagnosisLevelNumber)
        {
            return Service.GetForDiagnosisLevelJson(diagnosisLevelNumber);
        }
        
        public static async Task<string> GetForEvaluationAreaNumberJsonAsync(int areaNumber)
        {
            return await Service.GetForEvaluationAreaNumberJsonAsync(areaNumber);
        }
        
        public static async Task<string> GetForEvaluationQuestionJsonAsync(int evaluationQuestionNumber)
        {
            return await Service.GetForEvaluationQuestionJsonAsync(evaluationQuestionNumber);
        }
        
        public static async Task<string> GetForEvaluationPassageJsonAsync(int evaluationPassageNumber)
        {
            return await Service.GetForEvaluationPassageJsonAsync(evaluationPassageNumber);
        }
        
        public static async Task<string> GetForAspNetUsersJsonAsync(string userId)
        {
            return await Service.GetForAspNetUsersJsonAsync(userId);
        }
        
        public static async Task<string> GetForDiagnosisLevelJsonAsync(int diagnosisLevelNumber)
        {
            return await Service.GetForDiagnosisLevelJsonAsync(diagnosisLevelNumber);
        }
        
        public static DiagnosisEvaluationAnswer GetByKey(int evaluationAnswerNumber)
        {
            return Service.GetByKey(evaluationAnswerNumber);
        }
        
        public static string GetByKeyJson(int evaluationAnswerNumber)
        {
            return Service.GetByKeyJson(evaluationAnswerNumber);
        }
        
        public static async Task<DiagnosisEvaluationAnswer> GetByKeyAsync(int evaluationAnswerNumber)
        {
            return await Service.GetByKeyAsync(evaluationAnswerNumber);
        }
        
        public static async Task<string> GetByKeyJsonAsync(int evaluationAnswerNumber)
        {
            return await Service.GetByKeyJsonAsync(evaluationAnswerNumber);
        }
        
        public static DiagnosisEvaluationAnswer Insert(int areaNumber, int evaluationQuestionNumber, int evaluationPassageNumber, string userId, int diagnosisLevelNumber, string businessAnswer, int evidence, object diagEvaluationAnswer, object diagnosisDate, string evaluationAnswer, System.DateTime diagnosisEvaluationData, string inputStatus, string evaluationStatus, string evaluationResults)
        {
            // Insert 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            if ((diagEvaluationAnswer == null))
            {
                diagEvaluationAnswer = System.DBNull.Value;
            }
            if ((diagnosisDate == null))
            {
                diagnosisDate = System.DBNull.Value;
            }
            return Service.Insert(areaNumber, evaluationQuestionNumber, evaluationPassageNumber, userId, diagnosisLevelNumber, businessAnswer, evidence, diagEvaluationAnswer, diagnosisDate, evaluationAnswer, diagnosisEvaluationData, inputStatus, evaluationStatus, evaluationResults);
        }
        
        public static async Task<DiagnosisEvaluationAnswer> InsertAsync(int areaNumber, int evaluationQuestionNumber, int evaluationPassageNumber, string userId, int diagnosisLevelNumber, string businessAnswer, int evidence, object diagEvaluationAnswer, object diagnosisDate, string evaluationAnswer, System.DateTime diagnosisEvaluationData, string inputStatus, string evaluationStatus, string evaluationResults)
        {
            // InsertAsync 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            if ((diagEvaluationAnswer == null))
            {
                diagEvaluationAnswer = System.DBNull.Value;
            }
            if ((diagnosisDate == null))
            {
                diagnosisDate = System.DBNull.Value;
            }
            return await Service.InsertAsync(areaNumber, evaluationQuestionNumber, evaluationPassageNumber, userId, diagnosisLevelNumber, businessAnswer, evidence, diagEvaluationAnswer, diagnosisDate, evaluationAnswer, diagnosisEvaluationData, inputStatus, evaluationStatus, evaluationResults);
        }
        
        public new DiagnosisEvaluationAnswer Insert()
        {
            // Insert 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            return Insert(AreaNumber, EvaluationQuestionNumber, EvaluationPassageNumber, UserId, DiagnosisLevelNumber, BusinessAnswer, Evidence, DiagEvaluationAnswer, DiagnosisDate, EvaluationAnswer, DiagnosisEvaluationData, InputStatus, EvaluationStatus, EvaluationResults);
        }
        
        public async Task<DiagnosisEvaluationAnswer> InsertAsync()
        {
            // Insert 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            return await InsertAsync(AreaNumber, EvaluationQuestionNumber, EvaluationPassageNumber, UserId, DiagnosisLevelNumber, BusinessAnswer, Evidence, DiagEvaluationAnswer, DiagnosisDate, EvaluationAnswer, DiagnosisEvaluationData, InputStatus, EvaluationStatus, EvaluationResults);
        }
        
        public new int Update()
        {
            // 인수를 해당 파라메타에 옮긴다
            int evaluationAnswerNumberParam = this.EvaluationAnswerNumber;
            int areaNumberParam = this.AreaNumber;
            int evaluationQuestionNumberParam = this.EvaluationQuestionNumber;
            int evaluationPassageNumberParam = this.EvaluationPassageNumber;
            string userIdParam = this.UserId;
            int diagnosisLevelNumberParam = this.DiagnosisLevelNumber;
            string businessAnswerParam = this.BusinessAnswer;
            int evidenceParam = this.Evidence;
            object diagEvaluationAnswerParam;
            if ((this.IsDiagEvaluationAnswerNull() == false))
            {
                diagEvaluationAnswerParam = this.DiagEvaluationAnswer;
            }
            else
            {
                diagEvaluationAnswerParam = System.DBNull.Value;
            }
            object diagnosisDateParam;
            if ((this.IsDiagnosisDateNull() == false))
            {
                diagnosisDateParam = this.DiagnosisDate;
            }
            else
            {
                diagnosisDateParam = System.DBNull.Value;
            }
            string evaluationAnswerParam = this.EvaluationAnswer;
            System.DateTime diagnosisEvaluationDataParam = this.DiagnosisEvaluationData;
            string inputStatusParam = this.InputStatus;
            string evaluationStatusParam = this.EvaluationStatus;
            string evaluationResultsParam = this.EvaluationResults;
            // update 실행
            return Service.Update(evaluationAnswerNumberParam, areaNumberParam, evaluationQuestionNumberParam, evaluationPassageNumberParam, userIdParam, diagnosisLevelNumberParam, businessAnswerParam, evidenceParam, diagEvaluationAnswerParam, diagnosisDateParam, evaluationAnswerParam, diagnosisEvaluationDataParam, inputStatusParam, evaluationStatusParam, evaluationResultsParam);
        }
        
        public async Task<int> UpdateAsync()
        {
            // 인수를 해당 파라메타에 옮긴다
            int evaluationAnswerNumberParam = this.EvaluationAnswerNumber;
            int areaNumberParam = this.AreaNumber;
            int evaluationQuestionNumberParam = this.EvaluationQuestionNumber;
            int evaluationPassageNumberParam = this.EvaluationPassageNumber;
            string userIdParam = this.UserId;
            int diagnosisLevelNumberParam = this.DiagnosisLevelNumber;
            string businessAnswerParam = this.BusinessAnswer;
            int evidenceParam = this.Evidence;
            object diagEvaluationAnswerParam;
            if ((this.IsDiagEvaluationAnswerNull() == false))
            {
                diagEvaluationAnswerParam = this.DiagEvaluationAnswer;
            }
            else
            {
                diagEvaluationAnswerParam = System.DBNull.Value;
            }
            object diagnosisDateParam;
            if ((this.IsDiagnosisDateNull() == false))
            {
                diagnosisDateParam = this.DiagnosisDate;
            }
            else
            {
                diagnosisDateParam = System.DBNull.Value;
            }
            string evaluationAnswerParam = this.EvaluationAnswer;
            System.DateTime diagnosisEvaluationDataParam = this.DiagnosisEvaluationData;
            string inputStatusParam = this.InputStatus;
            string evaluationStatusParam = this.EvaluationStatus;
            string evaluationResultsParam = this.EvaluationResults;
            return await Service.UpdateAsync(evaluationAnswerNumberParam, areaNumberParam, evaluationQuestionNumberParam, evaluationPassageNumberParam, userIdParam, diagnosisLevelNumberParam, businessAnswerParam, evidenceParam, diagEvaluationAnswerParam, diagnosisDateParam, evaluationAnswerParam, diagnosisEvaluationDataParam, inputStatusParam, evaluationStatusParam, evaluationResultsParam);
        }
        
        public static int Update(int evaluationAnswerNumber, int areaNumber, int evaluationQuestionNumber, int evaluationPassageNumber, string userId, int diagnosisLevelNumber, string businessAnswer, int evidence, object diagEvaluationAnswer, object diagnosisDate, string evaluationAnswer, System.DateTime diagnosisEvaluationData, string inputStatus, string evaluationStatus, string evaluationResults)
        {
            if ((diagEvaluationAnswer == null))
            {
                diagEvaluationAnswer = System.DBNull.Value;
            }
            if ((diagnosisDate == null))
            {
                diagnosisDate = System.DBNull.Value;
            }
            return Service.Update(evaluationAnswerNumber, areaNumber, evaluationQuestionNumber, evaluationPassageNumber, userId, diagnosisLevelNumber, businessAnswer, evidence, diagEvaluationAnswer, diagnosisDate, evaluationAnswer, diagnosisEvaluationData, inputStatus, evaluationStatus, evaluationResults);
        }
        
        public static async Task<int> UpdateAsync(int evaluationAnswerNumber, int areaNumber, int evaluationQuestionNumber, int evaluationPassageNumber, string userId, int diagnosisLevelNumber, string businessAnswer, int evidence, object diagEvaluationAnswer, object diagnosisDate, string evaluationAnswer, System.DateTime diagnosisEvaluationData, string inputStatus, string evaluationStatus, string evaluationResults)
        {
            if ((diagEvaluationAnswer == null))
            {
                diagEvaluationAnswer = System.DBNull.Value;
            }
            if ((diagnosisDate == null))
            {
                diagnosisDate = System.DBNull.Value;
            }
            return await Service.UpdateAsync(evaluationAnswerNumber, areaNumber, evaluationQuestionNumber, evaluationPassageNumber, userId, diagnosisLevelNumber, businessAnswer, evidence, diagEvaluationAnswer, diagnosisDate, evaluationAnswer, diagnosisEvaluationData, inputStatus, evaluationStatus, evaluationResults);
        }
        
        public static int Delete(int evaluationAnswerNumber)
        {
            return Service.Delete(evaluationAnswerNumber);
        }
        
        public static async Task<int> DeleteAsync(int evaluationAnswerNumber)
        {
            return await Service.DeleteAsync(evaluationAnswerNumber);
        }
        
        public new int Delete()
        {
            return Service.Delete(EvaluationAnswerNumber);
        }
        
        public async Task<int> DeleteAsync()
        {
            return await Service.DeleteAsync(EvaluationAnswerNumber);
        }
    }
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbManager
{
    using System;
    using System.Runtime.Serialization;
    using System.Data;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using System.Transactions;
    using SoftBand.EntityManager;
    
    
    // Table('DiagnosisEvaluationAnswer')  Service class
    // Do not add or change code here.
    public partial class DiagnosisEvaluationAnswerService : SoftBand.EntityManager.Service
    {
        
        public DiagnosisEvaluationAnswerSet GetAll()
        {
            return ((DiagnosisEvaluationAnswerSet)(this.GetAll("DiagnosisEvaluationAnswer", typeof(DiagnosisEvaluationAnswerSet))));
        }
        
        public string GetAllJson()
        {
            return this.GetAllJson("DiagnosisEvaluationAnswer");
        }
        
        public async Task<DiagnosisEvaluationAnswerSet> GetAllAsync()
        {
            return ((DiagnosisEvaluationAnswerSet)(await this.GetAllAsync("DiagnosisEvaluationAnswer", typeof(DiagnosisEvaluationAnswerSet))));
        }
        
        public async Task<string> GetAllJsonAsync()
        {
            return await this.GetAllJsonAsync("DiagnosisEvaluationAnswer");
        }
        
        public DiagnosisEvaluationAnswerSet GetForEvaluationAreaNumber(int areaNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [DiagnosisEvaluationAnswer] WHERE AreaNumber = @areaNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "areaNumber";
            AddParameters(selectCmd, paraNames, areaNumber);
            DiagnosisEvaluationAnswerSet entitySet = ((DiagnosisEvaluationAnswerSet)(this.GetEntitySet(selectCmd, typeof(DiagnosisEvaluationAnswerSet))));
            selectCmd.Dispose();
            return entitySet;
        }
        
        public DiagnosisEvaluationAnswerSet GetForEvaluationQuestion(int evaluationQuestionNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [DiagnosisEvaluationAnswer] WHERE EvaluationQuestionNumber = @evalu" +
                "ationQuestionNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "evaluationQuestionNumber";
            AddParameters(selectCmd, paraNames, evaluationQuestionNumber);
            DiagnosisEvaluationAnswerSet entitySet = ((DiagnosisEvaluationAnswerSet)(this.GetEntitySet(selectCmd, typeof(DiagnosisEvaluationAnswerSet))));
            selectCmd.Dispose();
            return entitySet;
        }
        
        public DiagnosisEvaluationAnswerSet GetForEvaluationPassage(int evaluationPassageNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [DiagnosisEvaluationAnswer] WHERE EvaluationPassageNumber = @evalua" +
                "tionPassageNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "evaluationPassageNumber";
            AddParameters(selectCmd, paraNames, evaluationPassageNumber);
            DiagnosisEvaluationAnswerSet entitySet = ((DiagnosisEvaluationAnswerSet)(this.GetEntitySet(selectCmd, typeof(DiagnosisEvaluationAnswerSet))));
            selectCmd.Dispose();
            return entitySet;
        }
        
        public DiagnosisEvaluationAnswerSet GetForAspNetUsers(string userId)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [DiagnosisEvaluationAnswer] WHERE UserId = @userId";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "userId";
            AddParameters(selectCmd, paraNames, userId);
            DiagnosisEvaluationAnswerSet entitySet = ((DiagnosisEvaluationAnswerSet)(this.GetEntitySet(selectCmd, typeof(DiagnosisEvaluationAnswerSet))));
            selectCmd.Dispose();
            return entitySet;
        }
        
        public DiagnosisEvaluationAnswerSet GetForDiagnosisLevel(int diagnosisLevelNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [DiagnosisEvaluationAnswer] WHERE DiagnosisLevelNumber = @diagnosis" +
                "LevelNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "diagnosisLevelNumber";
            AddParameters(selectCmd, paraNames, diagnosisLevelNumber);
            DiagnosisEvaluationAnswerSet entitySet = ((DiagnosisEvaluationAnswerSet)(this.GetEntitySet(selectCmd, typeof(DiagnosisEvaluationAnswerSet))));
            selectCmd.Dispose();
            return entitySet;
        }
        
        public async Task<DiagnosisEvaluationAnswerSet> GetForEvaluationAreaNumberAsync(int areaNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [DiagnosisEvaluationAnswer] WHERE AreaNumber = @areaNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "areaNumber";
            AddParameters(selectCmd, paraNames, areaNumber);
            DiagnosisEvaluationAnswerSet entitySet = ((DiagnosisEvaluationAnswerSet)(await this.GetEntitySetAsync(selectCmd, typeof(DiagnosisEvaluationAnswerSet))));
            selectCmd.Dispose();
            return entitySet;
        }
        
        public async Task<DiagnosisEvaluationAnswerSet> GetForEvaluationQuestionAsync(int evaluationQuestionNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [DiagnosisEvaluationAnswer] WHERE EvaluationQuestionNumber = @evalu" +
                "ationQuestionNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "evaluationQuestionNumber";
            AddParameters(selectCmd, paraNames, evaluationQuestionNumber);
            DiagnosisEvaluationAnswerSet entitySet = ((DiagnosisEvaluationAnswerSet)(await this.GetEntitySetAsync(selectCmd, typeof(DiagnosisEvaluationAnswerSet))));
            selectCmd.Dispose();
            return entitySet;
        }
        
        public async Task<DiagnosisEvaluationAnswerSet> GetForEvaluationPassageAsync(int evaluationPassageNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [DiagnosisEvaluationAnswer] WHERE EvaluationPassageNumber = @evalua" +
                "tionPassageNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "evaluationPassageNumber";
            AddParameters(selectCmd, paraNames, evaluationPassageNumber);
            DiagnosisEvaluationAnswerSet entitySet = ((DiagnosisEvaluationAnswerSet)(await this.GetEntitySetAsync(selectCmd, typeof(DiagnosisEvaluationAnswerSet))));
            selectCmd.Dispose();
            return entitySet;
        }
        
        public async Task<DiagnosisEvaluationAnswerSet> GetForAspNetUsersAsync(string userId)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [DiagnosisEvaluationAnswer] WHERE UserId = @userId";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "userId";
            AddParameters(selectCmd, paraNames, userId);
            DiagnosisEvaluationAnswerSet entitySet = ((DiagnosisEvaluationAnswerSet)(await this.GetEntitySetAsync(selectCmd, typeof(DiagnosisEvaluationAnswerSet))));
            selectCmd.Dispose();
            return entitySet;
        }
        
        public async Task<DiagnosisEvaluationAnswerSet> GetForDiagnosisLevelAsync(int diagnosisLevelNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [DiagnosisEvaluationAnswer] WHERE DiagnosisLevelNumber = @diagnosis" +
                "LevelNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "diagnosisLevelNumber";
            AddParameters(selectCmd, paraNames, diagnosisLevelNumber);
            DiagnosisEvaluationAnswerSet entitySet = ((DiagnosisEvaluationAnswerSet)(await this.GetEntitySetAsync(selectCmd, typeof(DiagnosisEvaluationAnswerSet))));
            selectCmd.Dispose();
            return entitySet;
        }
        
        public string GetForEvaluationAreaNumberJson(int areaNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [DiagnosisEvaluationAnswer] WHERE AreaNumber = @areaNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "areaNumber";
            AddParameters(selectCmd, paraNames, areaNumber);
            return  this.GetJsonDataSet(selectCmd);
        }
        
        public string GetForEvaluationQuestionJson(int evaluationQuestionNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [DiagnosisEvaluationAnswer] WHERE EvaluationQuestionNumber = @evalu" +
                "ationQuestionNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "evaluationQuestionNumber";
            AddParameters(selectCmd, paraNames, evaluationQuestionNumber);
            return  this.GetJsonDataSet(selectCmd);
        }
        
        public string GetForEvaluationPassageJson(int evaluationPassageNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [DiagnosisEvaluationAnswer] WHERE EvaluationPassageNumber = @evalua" +
                "tionPassageNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "evaluationPassageNumber";
            AddParameters(selectCmd, paraNames, evaluationPassageNumber);
            return  this.GetJsonDataSet(selectCmd);
        }
        
        public string GetForAspNetUsersJson(string userId)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [DiagnosisEvaluationAnswer] WHERE UserId = @userId";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "userId";
            AddParameters(selectCmd, paraNames, userId);
            return  this.GetJsonDataSet(selectCmd);
        }
        
        public string GetForDiagnosisLevelJson(int diagnosisLevelNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [DiagnosisEvaluationAnswer] WHERE DiagnosisLevelNumber = @diagnosis" +
                "LevelNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "diagnosisLevelNumber";
            AddParameters(selectCmd, paraNames, diagnosisLevelNumber);
            return  this.GetJsonDataSet(selectCmd);
        }
        
        public async Task<string> GetForEvaluationAreaNumberJsonAsync(int areaNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [DiagnosisEvaluationAnswer] WHERE AreaNumber = @areaNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "areaNumber";
            AddParameters(selectCmd, paraNames, areaNumber);
            return await this.GetJsonDataSetAsync(selectCmd);
        }
        
        public async Task<string> GetForEvaluationQuestionJsonAsync(int evaluationQuestionNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [DiagnosisEvaluationAnswer] WHERE EvaluationQuestionNumber = @evalu" +
                "ationQuestionNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "evaluationQuestionNumber";
            AddParameters(selectCmd, paraNames, evaluationQuestionNumber);
            return await this.GetJsonDataSetAsync(selectCmd);
        }
        
        public async Task<string> GetForEvaluationPassageJsonAsync(int evaluationPassageNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [DiagnosisEvaluationAnswer] WHERE EvaluationPassageNumber = @evalua" +
                "tionPassageNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "evaluationPassageNumber";
            AddParameters(selectCmd, paraNames, evaluationPassageNumber);
            return await this.GetJsonDataSetAsync(selectCmd);
        }
        
        public async Task<string> GetForAspNetUsersJsonAsync(string userId)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [DiagnosisEvaluationAnswer] WHERE UserId = @userId";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "userId";
            AddParameters(selectCmd, paraNames, userId);
            return await this.GetJsonDataSetAsync(selectCmd);
        }
        
        public async Task<string> GetForDiagnosisLevelJsonAsync(int diagnosisLevelNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [DiagnosisEvaluationAnswer] WHERE DiagnosisLevelNumber = @diagnosis" +
                "LevelNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "diagnosisLevelNumber";
            AddParameters(selectCmd, paraNames, diagnosisLevelNumber);
            return await this.GetJsonDataSetAsync(selectCmd);
        }
        
        public DiagnosisEvaluationAnswer GetByKey(int evaluationAnswerNumber)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM DiagnosisEvaluationAnswer WHERE EvaluationAnswerNumber = @evaluatio" +
                "nAnswerNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "evaluationAnswerNumber";
            AddParameters(selectCmd, paraNames, evaluationAnswerNumber);
            // 
            DiagnosisEvaluationAnswer entity = ((DiagnosisEvaluationAnswer)(this.GetEntity(selectCmd, typeof(DiagnosisEvaluationAnswerSet))));
            selectCmd.Dispose();
            return entity;
        }
        
        public  string GetByKeyJson(int evaluationAnswerNumber)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM DiagnosisEvaluationAnswer WHERE EvaluationAnswerNumber = @evaluatio" +
                "nAnswerNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "evaluationAnswerNumber";
            AddParameters(selectCmd, paraNames, evaluationAnswerNumber);
            // 
            return this.GetJsonDataSet(selectCmd);
        }
        
        public async Task<DiagnosisEvaluationAnswer> GetByKeyAsync(int evaluationAnswerNumber)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM DiagnosisEvaluationAnswer WHERE EvaluationAnswerNumber = @evaluatio" +
                "nAnswerNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "evaluationAnswerNumber";
            AddParameters(selectCmd, paraNames, evaluationAnswerNumber);
            // 
            // GetByKeyAsync 를 호출한다
            DiagnosisEvaluationAnswer entity = ((DiagnosisEvaluationAnswer)(await this.GetEntityAsync(selectCmd, typeof(DiagnosisEvaluationAnswerSet))));
            selectCmd.Dispose();
            return entity;
        }
        
        public async Task<string> GetByKeyJsonAsync(int evaluationAnswerNumber)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM DiagnosisEvaluationAnswer WHERE EvaluationAnswerNumber = @evaluatio" +
                "nAnswerNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "evaluationAnswerNumber";
            AddParameters(selectCmd, paraNames, evaluationAnswerNumber);
            // 
            return await this.GetJsonDataSetAsync(selectCmd);
        }
        
        public DiagnosisEvaluationAnswer Insert(int areaNumber, int evaluationQuestionNumber, int evaluationPassageNumber, string userId, int diagnosisLevelNumber, string businessAnswer, int evidence, object diagEvaluationAnswer, object diagnosisDate, string evaluationAnswer, System.DateTime diagnosisEvaluationData, string inputStatus, string evaluationStatus, string evaluationResults)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand insertCommand = DbCommandFactory.CreateDbCommand();
            insertCommand.CommandText = @"INSERT INTO DiagnosisEvaluationAnswer(AreaNumber, EvaluationQuestionNumber, EvaluationPassageNumber, UserId, DiagnosisLevelNumber, BusinessAnswer, Evidence, DiagEvaluationAnswer, DiagnosisDate, EvaluationAnswer, DiagnosisEvaluationData, InputStatus, EvaluationStatus, EvaluationResults) OUTPUT INSERTED.EvaluationAnswerNumber
VALUES (@areaNumber, @evaluationQuestionNumber, @evaluationPassageNumber, @userId, @diagnosisLevelNumber, @businessAnswer, @evidence, @diagEvaluationAnswer, @diagnosisDate, @evaluationAnswer, @diagnosisEvaluationData, @inputStatus, @evaluationStatus, @evaluationResults) ";
            insertCommand.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "areaNumber,evaluationQuestionNumber,evaluationPassageNumber,userId,diagnosisLevel" +
                "Number,businessAnswer,evidence,diagEvaluationAnswer,diagnosisDate,evaluationAnsw" +
                "er,diagnosisEvaluationData,inputStatus,evaluationStatus,evaluationResults";
            AddParameters(insertCommand, paraNames, areaNumber, evaluationQuestionNumber, evaluationPassageNumber, userId, diagnosisLevelNumber, businessAnswer, evidence, diagEvaluationAnswer, diagnosisDate, evaluationAnswer, diagnosisEvaluationData, inputStatus, evaluationStatus, evaluationResults);
            // 
            // Insert 를 호출한다
            DiagnosisEvaluationAnswer entity = ((DiagnosisEvaluationAnswer)(this.GetByKey(System.Convert.ToInt32(this.ExecuteScalar(insertCommand)))));
            insertCommand.Dispose();
            return entity;
        }
        
        public async Task<DiagnosisEvaluationAnswer> InsertAsync(int areaNumber, int evaluationQuestionNumber, int evaluationPassageNumber, string userId, int diagnosisLevelNumber, string businessAnswer, int evidence, object diagEvaluationAnswer, object diagnosisDate, string evaluationAnswer, System.DateTime diagnosisEvaluationData, string inputStatus, string evaluationStatus, string evaluationResults)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand insertCommand = DbCommandFactory.CreateDbCommand();
            insertCommand.CommandText = @"INSERT INTO DiagnosisEvaluationAnswer(AreaNumber, EvaluationQuestionNumber, EvaluationPassageNumber, UserId, DiagnosisLevelNumber, BusinessAnswer, Evidence, DiagEvaluationAnswer, DiagnosisDate, EvaluationAnswer, DiagnosisEvaluationData, InputStatus, EvaluationStatus, EvaluationResults) OUTPUT INSERTED.EvaluationAnswerNumber
VALUES (@areaNumber, @evaluationQuestionNumber, @evaluationPassageNumber, @userId, @diagnosisLevelNumber, @businessAnswer, @evidence, @diagEvaluationAnswer, @diagnosisDate, @evaluationAnswer, @diagnosisEvaluationData, @inputStatus, @evaluationStatus, @evaluationResults) ";
            insertCommand.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "areaNumber,evaluationQuestionNumber,evaluationPassageNumber,userId,diagnosisLevel" +
                "Number,businessAnswer,evidence,diagEvaluationAnswer,diagnosisDate,evaluationAnsw" +
                "er,diagnosisEvaluationData,inputStatus,evaluationStatus,evaluationResults";
            AddParameters(insertCommand, paraNames, areaNumber, evaluationQuestionNumber, evaluationPassageNumber, userId, diagnosisLevelNumber, businessAnswer, evidence, diagEvaluationAnswer, diagnosisDate, evaluationAnswer, diagnosisEvaluationData, inputStatus, evaluationStatus, evaluationResults);
            // 
            // InsertAsync 를 호출한다
            DiagnosisEvaluationAnswer entity = ((DiagnosisEvaluationAnswer)(await this.GetByKeyAsync(System.Convert.ToInt32(await this.ExecuteScalarAsync(insertCommand)))));
            insertCommand.Dispose();
            return entity;
        }
        
        public int Update(int evaluationAnswerNumber, int areaNumber, int evaluationQuestionNumber, int evaluationPassageNumber, string userId, int diagnosisLevelNumber, string businessAnswer, int evidence, object diagEvaluationAnswer, object diagnosisDate, string evaluationAnswer, System.DateTime diagnosisEvaluationData, string inputStatus, string evaluationStatus, string evaluationResults)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand updateCmd = DbCommandFactory.CreateDbCommand();
            updateCmd.CommandText = @"UPDATE DiagnosisEvaluationAnswer SET AreaNumber = @areaNumber, EvaluationQuestionNumber = @evaluationQuestionNumber, EvaluationPassageNumber = @evaluationPassageNumber, UserId = @userId, DiagnosisLevelNumber = @diagnosisLevelNumber, BusinessAnswer = @businessAnswer, Evidence = @evidence, DiagEvaluationAnswer = @diagEvaluationAnswer, DiagnosisDate = @diagnosisDate, EvaluationAnswer = @evaluationAnswer, DiagnosisEvaluationData = @diagnosisEvaluationData, InputStatus = @inputStatus, EvaluationStatus = @evaluationStatus, EvaluationResults = @evaluationResults WHERE EvaluationAnswerNumber = @evaluationAnswerNumber";
            updateCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = @"evaluationAnswerNumber,areaNumber,evaluationQuestionNumber,evaluationPassageNumber,userId,diagnosisLevelNumber,businessAnswer,evidence,diagEvaluationAnswer,diagnosisDate,evaluationAnswer,diagnosisEvaluationData,inputStatus,evaluationStatus,evaluationResults";
            AddParameters(updateCmd, paraNames, evaluationAnswerNumber, areaNumber, evaluationQuestionNumber, evaluationPassageNumber, userId, diagnosisLevelNumber, businessAnswer, evidence, diagEvaluationAnswer, diagnosisDate, evaluationAnswer, diagnosisEvaluationData, inputStatus, evaluationStatus, evaluationResults);
            // 
            // Update 를 호출한다
            int executeCnt = this.ExecuteNonQuery(updateCmd);
            updateCmd.Dispose();
            return executeCnt;
        }
        
        public async Task<int> UpdateAsync(int evaluationAnswerNumber, int areaNumber, int evaluationQuestionNumber, int evaluationPassageNumber, string userId, int diagnosisLevelNumber, string businessAnswer, int evidence, object diagEvaluationAnswer, object diagnosisDate, string evaluationAnswer, System.DateTime diagnosisEvaluationData, string inputStatus, string evaluationStatus, string evaluationResults)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand updateCmd = DbCommandFactory.CreateDbCommand();
            updateCmd.CommandText = @"UPDATE DiagnosisEvaluationAnswer SET AreaNumber = @areaNumber, EvaluationQuestionNumber = @evaluationQuestionNumber, EvaluationPassageNumber = @evaluationPassageNumber, UserId = @userId, DiagnosisLevelNumber = @diagnosisLevelNumber, BusinessAnswer = @businessAnswer, Evidence = @evidence, DiagEvaluationAnswer = @diagEvaluationAnswer, DiagnosisDate = @diagnosisDate, EvaluationAnswer = @evaluationAnswer, DiagnosisEvaluationData = @diagnosisEvaluationData, InputStatus = @inputStatus, EvaluationStatus = @evaluationStatus, EvaluationResults = @evaluationResults WHERE EvaluationAnswerNumber = @evaluationAnswerNumber";
            updateCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = @"evaluationAnswerNumber,areaNumber,evaluationQuestionNumber,evaluationPassageNumber,userId,diagnosisLevelNumber,businessAnswer,evidence,diagEvaluationAnswer,diagnosisDate,evaluationAnswer,diagnosisEvaluationData,inputStatus,evaluationStatus,evaluationResults";
            AddParameters(updateCmd, paraNames, evaluationAnswerNumber, areaNumber, evaluationQuestionNumber, evaluationPassageNumber, userId, diagnosisLevelNumber, businessAnswer, evidence, diagEvaluationAnswer, diagnosisDate, evaluationAnswer, diagnosisEvaluationData, inputStatus, evaluationStatus, evaluationResults);
            // 
            // Update 를 호출한다
            int executeCnt = await this.ExecuteNonQueryAsync(updateCmd);
            updateCmd.Dispose();
            return executeCnt;
        }
        
        public int Delete(int evaluationAnswerNumber)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand deleteCmd = DbCommandFactory.CreateDbCommand();
            deleteCmd.CommandText = "DELETE FROM DiagnosisEvaluationAnswer WHERE EvaluationAnswerNumber = @evaluationA" +
                "nswerNumber";
            deleteCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "evaluationAnswerNumber";
            AddParameters(deleteCmd, paraNames, evaluationAnswerNumber);
            // 
            // Delete 를 호출한다
            int executeCnt = this.ExecuteNonQuery(deleteCmd);
            deleteCmd.Dispose();
            return executeCnt;
        }
        
        public async Task<int> DeleteAsync(int evaluationAnswerNumber)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand deleteCmd = DbCommandFactory.CreateDbCommand();
            deleteCmd.CommandText = "DELETE FROM DiagnosisEvaluationAnswer WHERE EvaluationAnswerNumber = @evaluationA" +
                "nswerNumber";
            deleteCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "evaluationAnswerNumber";
            AddParameters(deleteCmd, paraNames, evaluationAnswerNumber);
            // 
            // Delete 를 호출한다
            int executeCnt = await this.ExecuteNonQueryAsync(deleteCmd);
            deleteCmd.Dispose();
            return executeCnt;
        }
    }
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbManager
{
    using System;
    using System.Runtime.Serialization;
    using System.Data;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using System.Transactions;
    using SoftBand.EntityManager;
    
    
    // Table('DiagnosisEvaluationAnswer') EntitySet class
    // Do not add or change code here.
    [System.Serializable()]
    public partial class DiagnosisEvaluationAnswerSet : SoftBand.EntityManager.EntitySet, System.Collections.IEnumerable
    {
        
        // Constructor
        public DiagnosisEvaluationAnswerSet() : 
                this(null)
        {
        }
        
        // basic constructor
        protected DiagnosisEvaluationAnswerSet(object state)
        {
            this.Setup();
        }
        
        // remoting constructor...
        protected DiagnosisEvaluationAnswerSet(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context)
        {
            this.Setup();
        }
        
        public DiagnosisEvaluationAnswerBoundCollection Entities
        {
            get
            {
                return this.GetBoundCollection();
            }
        }
        
        // shared object initialization...
        private void Setup()
        {
            this.EntityType = typeof(DiagnosisEvaluationAnswer);
        }
        
        private DiagnosisEvaluationAnswerBoundCollection GetBoundCollection()
        {
            return this.GetBoundCollection(0);
        }
        
        private DiagnosisEvaluationAnswerBoundCollection GetBoundCollection(int tableIndex)
        {
            return ((DiagnosisEvaluationAnswerBoundCollection)(this.GetBoundCollection(this, tableIndex, typeof(DiagnosisEvaluationAnswerBoundCollection))));
        }
        
        public partial class DiagnosisEvaluationAnswerBoundCollection : SoftBand.EntityManager.EntityBoundCollection
        {
            
            public new DiagnosisEvaluationAnswer this[int index]
            {
                get
                {
                    return ((DiagnosisEvaluationAnswer)(this.EntitySet.GetEntity(this.TableIndex, index)));
                }
            }
        }
    }
}
