//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbManager
{
    using System;
    using System.Runtime.Serialization;
    using System.Data;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using System.Transactions;
    using SoftBand.EntityManager;
    
    
    // Table('EvaluationComment') Entity class
    // Do not add or change code here.
    [System.Serializable()]
    public partial class EvaluationComment : SoftBand.EntityManager.Entity
    {
        
        public EvaluationComment()
        {
            this.DefineColumns(5);
        }
        
        public int CommentNumber
        {
            get
            {
                return ((int)(this[0]));
            }
            set
            {
                this[0] = value;
            }
        }
        
        public int EvaluationAnswerNumber
        {
            get
            {
                return ((int)(this[1]));
            }
            set
            {
                this[1] = value;
            }
        }
        
        public int EvaluationSelectionNumber
        {
            get
            {
                return ((int)(this[2]));
            }
            set
            {
                this[2] = value;
            }
        }
        
        public string EvaluationComments
        {
            get
            {
                return ((string)(this[3]));
            }
            set
            {
                this[3] = value;
            }
        }
        
        public System.DateTime CoomnetDate
        {
            get
            {
                return ((System.DateTime)(this[4]));
            }
            set
            {
                this[4] = value;
            }
        }
        
        public static EvaluationCommentService Service
        {
            get
            {
                return ((EvaluationCommentService)(GetServiceObject(typeof(EvaluationComment), typeof(EvaluationCommentService))));
            }
        }
        
        public static EvaluationCommentSet GetAll()
        {
            return Service.GetAll();
        }
        
        public static string GetAllJson()
        {
            return Service.GetAllJson();
        }
        
        public static async Task<EvaluationCommentSet> GetAllAsync()
        {
            return await Service.GetAllAsync();
        }
        
        public static async Task<string> GetAllJsonAsync()
        {
            return await Service.GetAllJsonAsync();
        }
        
        public static EvaluationCommentSet GetForDiagnosisEvaluationAnswer(int evaluationAnswerNumber)
        {
            return Service.GetForDiagnosisEvaluationAnswer(evaluationAnswerNumber);
        }
        
        public static EvaluationCommentSet GetForEvaluationSelection(int evaluationSelectionNumber)
        {
            return Service.GetForEvaluationSelection(evaluationSelectionNumber);
        }
        
        public static async Task<EvaluationCommentSet> GetForDiagnosisEvaluationAnswerAsync(int evaluationAnswerNumber)
        {
            return await Service.GetForDiagnosisEvaluationAnswerAsync(evaluationAnswerNumber);
        }
        
        public static async Task<EvaluationCommentSet> GetForEvaluationSelectionAsync(int evaluationSelectionNumber)
        {
            return await Service.GetForEvaluationSelectionAsync(evaluationSelectionNumber);
        }
        
        public static string GetForDiagnosisEvaluationAnswerJson(int evaluationAnswerNumber)
        {
            return Service.GetForDiagnosisEvaluationAnswerJson(evaluationAnswerNumber);
        }
        
        public static string GetForEvaluationSelectionJson(int evaluationSelectionNumber)
        {
            return Service.GetForEvaluationSelectionJson(evaluationSelectionNumber);
        }
        
        public static async Task<string> GetForDiagnosisEvaluationAnswerJsonAsync(int evaluationAnswerNumber)
        {
            return await Service.GetForDiagnosisEvaluationAnswerJsonAsync(evaluationAnswerNumber);
        }
        
        public static async Task<string> GetForEvaluationSelectionJsonAsync(int evaluationSelectionNumber)
        {
            return await Service.GetForEvaluationSelectionJsonAsync(evaluationSelectionNumber);
        }
        
        public static EvaluationComment GetByKey(int commentNumber)
        {
            return Service.GetByKey(commentNumber);
        }
        
        public static string GetByKeyJson(int commentNumber)
        {
            return Service.GetByKeyJson(commentNumber);
        }
        
        public static async Task<EvaluationComment> GetByKeyAsync(int commentNumber)
        {
            return await Service.GetByKeyAsync(commentNumber);
        }
        
        public static async Task<string> GetByKeyJsonAsync(int commentNumber)
        {
            return await Service.GetByKeyJsonAsync(commentNumber);
        }
        
        public static EvaluationComment Insert(int evaluationAnswerNumber, int evaluationSelectionNumber, string evaluationComments, System.DateTime coomnetDate)
        {
            // Insert 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            return Service.Insert(evaluationAnswerNumber, evaluationSelectionNumber, evaluationComments, coomnetDate);
        }
        
        public static async Task<EvaluationComment> InsertAsync(int evaluationAnswerNumber, int evaluationSelectionNumber, string evaluationComments, System.DateTime coomnetDate)
        {
            // InsertAsync 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            return await Service.InsertAsync(evaluationAnswerNumber, evaluationSelectionNumber, evaluationComments, coomnetDate);
        }
        
        public new EvaluationComment Insert()
        {
            // Insert 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            return Insert(EvaluationAnswerNumber, EvaluationSelectionNumber, EvaluationComments, CoomnetDate);
        }
        
        public async Task<EvaluationComment> InsertAsync()
        {
            // Insert 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            return await InsertAsync(EvaluationAnswerNumber, EvaluationSelectionNumber, EvaluationComments, CoomnetDate);
        }
        
        public new int Update()
        {
            // 인수를 해당 파라메타에 옮긴다
            int commentNumberParam = this.CommentNumber;
            int evaluationAnswerNumberParam = this.EvaluationAnswerNumber;
            int evaluationSelectionNumberParam = this.EvaluationSelectionNumber;
            string evaluationCommentsParam = this.EvaluationComments;
            System.DateTime coomnetDateParam = this.CoomnetDate;
            // update 실행
            return Service.Update(commentNumberParam, evaluationAnswerNumberParam, evaluationSelectionNumberParam, evaluationCommentsParam, coomnetDateParam);
        }
        
        public async Task<int> UpdateAsync()
        {
            // 인수를 해당 파라메타에 옮긴다
            int commentNumberParam = this.CommentNumber;
            int evaluationAnswerNumberParam = this.EvaluationAnswerNumber;
            int evaluationSelectionNumberParam = this.EvaluationSelectionNumber;
            string evaluationCommentsParam = this.EvaluationComments;
            System.DateTime coomnetDateParam = this.CoomnetDate;
            return await Service.UpdateAsync(commentNumberParam, evaluationAnswerNumberParam, evaluationSelectionNumberParam, evaluationCommentsParam, coomnetDateParam);
        }
        
        public static int Update(int commentNumber, int evaluationAnswerNumber, int evaluationSelectionNumber, string evaluationComments, System.DateTime coomnetDate)
        {
            return Service.Update(commentNumber, evaluationAnswerNumber, evaluationSelectionNumber, evaluationComments, coomnetDate);
        }
        
        public static async Task<int> UpdateAsync(int commentNumber, int evaluationAnswerNumber, int evaluationSelectionNumber, string evaluationComments, System.DateTime coomnetDate)
        {
            return await Service.UpdateAsync(commentNumber, evaluationAnswerNumber, evaluationSelectionNumber, evaluationComments, coomnetDate);
        }
        
        public static int Delete(int commentNumber)
        {
            return Service.Delete(commentNumber);
        }
        
        public static async Task<int> DeleteAsync(int commentNumber)
        {
            return await Service.DeleteAsync(commentNumber);
        }
        
        public new int Delete()
        {
            return Service.Delete(CommentNumber);
        }
        
        public async Task<int> DeleteAsync()
        {
            return await Service.DeleteAsync(CommentNumber);
        }
    }
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbManager
{
    using System;
    using System.Runtime.Serialization;
    using System.Data;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using System.Transactions;
    using SoftBand.EntityManager;
    
    
    // Table('EvaluationComment')  Service class
    // Do not add or change code here.
    public partial class EvaluationCommentService : SoftBand.EntityManager.Service
    {
        
        public EvaluationCommentSet GetAll()
        {
            return ((EvaluationCommentSet)(this.GetAll("EvaluationComment", typeof(EvaluationCommentSet))));
        }
        
        public string GetAllJson()
        {
            return this.GetAllJson("EvaluationComment");
        }
        
        public async Task<EvaluationCommentSet> GetAllAsync()
        {
            return ((EvaluationCommentSet)(await this.GetAllAsync("EvaluationComment", typeof(EvaluationCommentSet))));
        }
        
        public async Task<string> GetAllJsonAsync()
        {
            return await this.GetAllJsonAsync("EvaluationComment");
        }
        
        public EvaluationCommentSet GetForDiagnosisEvaluationAnswer(int evaluationAnswerNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [EvaluationComment] WHERE EvaluationAnswerNumber = @evaluationAnswe" +
                "rNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "evaluationAnswerNumber";
            AddParameters(selectCmd, paraNames, evaluationAnswerNumber);
            EvaluationCommentSet entitySet = ((EvaluationCommentSet)(this.GetEntitySet(selectCmd, typeof(EvaluationCommentSet))));
            selectCmd.Dispose();
            return entitySet;
        }
        
        public EvaluationCommentSet GetForEvaluationSelection(int evaluationSelectionNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [EvaluationComment] WHERE EvaluationSelectionNumber = @evaluationSe" +
                "lectionNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "evaluationSelectionNumber";
            AddParameters(selectCmd, paraNames, evaluationSelectionNumber);
            EvaluationCommentSet entitySet = ((EvaluationCommentSet)(this.GetEntitySet(selectCmd, typeof(EvaluationCommentSet))));
            selectCmd.Dispose();
            return entitySet;
        }
        
        public async Task<EvaluationCommentSet> GetForDiagnosisEvaluationAnswerAsync(int evaluationAnswerNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [EvaluationComment] WHERE EvaluationAnswerNumber = @evaluationAnswe" +
                "rNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "evaluationAnswerNumber";
            AddParameters(selectCmd, paraNames, evaluationAnswerNumber);
            EvaluationCommentSet entitySet = ((EvaluationCommentSet)(await this.GetEntitySetAsync(selectCmd, typeof(EvaluationCommentSet))));
            selectCmd.Dispose();
            return entitySet;
        }
        
        public async Task<EvaluationCommentSet> GetForEvaluationSelectionAsync(int evaluationSelectionNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [EvaluationComment] WHERE EvaluationSelectionNumber = @evaluationSe" +
                "lectionNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "evaluationSelectionNumber";
            AddParameters(selectCmd, paraNames, evaluationSelectionNumber);
            EvaluationCommentSet entitySet = ((EvaluationCommentSet)(await this.GetEntitySetAsync(selectCmd, typeof(EvaluationCommentSet))));
            selectCmd.Dispose();
            return entitySet;
        }
        
        public string GetForDiagnosisEvaluationAnswerJson(int evaluationAnswerNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [EvaluationComment] WHERE EvaluationAnswerNumber = @evaluationAnswe" +
                "rNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "evaluationAnswerNumber";
            AddParameters(selectCmd, paraNames, evaluationAnswerNumber);
            return  this.GetJsonDataSet(selectCmd);
        }
        
        public string GetForEvaluationSelectionJson(int evaluationSelectionNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [EvaluationComment] WHERE EvaluationSelectionNumber = @evaluationSe" +
                "lectionNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "evaluationSelectionNumber";
            AddParameters(selectCmd, paraNames, evaluationSelectionNumber);
            return  this.GetJsonDataSet(selectCmd);
        }
        
        public async Task<string> GetForDiagnosisEvaluationAnswerJsonAsync(int evaluationAnswerNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [EvaluationComment] WHERE EvaluationAnswerNumber = @evaluationAnswe" +
                "rNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "evaluationAnswerNumber";
            AddParameters(selectCmd, paraNames, evaluationAnswerNumber);
            return await this.GetJsonDataSetAsync(selectCmd);
        }
        
        public async Task<string> GetForEvaluationSelectionJsonAsync(int evaluationSelectionNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [EvaluationComment] WHERE EvaluationSelectionNumber = @evaluationSe" +
                "lectionNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "evaluationSelectionNumber";
            AddParameters(selectCmd, paraNames, evaluationSelectionNumber);
            return await this.GetJsonDataSetAsync(selectCmd);
        }
        
        public EvaluationComment GetByKey(int commentNumber)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM EvaluationComment WHERE CommentNumber = @commentNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "commentNumber";
            AddParameters(selectCmd, paraNames, commentNumber);
            // 
            EvaluationComment entity = ((EvaluationComment)(this.GetEntity(selectCmd, typeof(EvaluationCommentSet))));
            selectCmd.Dispose();
            return entity;
        }
        
        public  string GetByKeyJson(int commentNumber)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM EvaluationComment WHERE CommentNumber = @commentNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "commentNumber";
            AddParameters(selectCmd, paraNames, commentNumber);
            // 
            return this.GetJsonDataSet(selectCmd);
        }
        
        public async Task<EvaluationComment> GetByKeyAsync(int commentNumber)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM EvaluationComment WHERE CommentNumber = @commentNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "commentNumber";
            AddParameters(selectCmd, paraNames, commentNumber);
            // 
            // GetByKeyAsync 를 호출한다
            EvaluationComment entity = ((EvaluationComment)(await this.GetEntityAsync(selectCmd, typeof(EvaluationCommentSet))));
            selectCmd.Dispose();
            return entity;
        }
        
        public async Task<string> GetByKeyJsonAsync(int commentNumber)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM EvaluationComment WHERE CommentNumber = @commentNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "commentNumber";
            AddParameters(selectCmd, paraNames, commentNumber);
            // 
            return await this.GetJsonDataSetAsync(selectCmd);
        }
        
        public EvaluationComment Insert(int evaluationAnswerNumber, int evaluationSelectionNumber, string evaluationComments, System.DateTime coomnetDate)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand insertCommand = DbCommandFactory.CreateDbCommand();
            insertCommand.CommandText = "INSERT INTO EvaluationComment(EvaluationAnswerNumber, EvaluationSelectionNumber, " +
                "EvaluationComments, CoomnetDate) OUTPUT INSERTED.CommentNumber\r\nVALUES (@evaluat" +
                "ionAnswerNumber, @evaluationSelectionNumber, @evaluationComments, @coomnetDate) " +
                "";
            insertCommand.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "evaluationAnswerNumber,evaluationSelectionNumber,evaluationComments,coomnetDate";
            AddParameters(insertCommand, paraNames, evaluationAnswerNumber, evaluationSelectionNumber, evaluationComments, coomnetDate);
            // 
            // Insert 를 호출한다
            EvaluationComment entity = ((EvaluationComment)(this.GetByKey(System.Convert.ToInt32(this.ExecuteScalar(insertCommand)))));
            insertCommand.Dispose();
            return entity;
        }
        
        public async Task<EvaluationComment> InsertAsync(int evaluationAnswerNumber, int evaluationSelectionNumber, string evaluationComments, System.DateTime coomnetDate)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand insertCommand = DbCommandFactory.CreateDbCommand();
            insertCommand.CommandText = "INSERT INTO EvaluationComment(EvaluationAnswerNumber, EvaluationSelectionNumber, " +
                "EvaluationComments, CoomnetDate) OUTPUT INSERTED.CommentNumber\r\nVALUES (@evaluat" +
                "ionAnswerNumber, @evaluationSelectionNumber, @evaluationComments, @coomnetDate) " +
                "";
            insertCommand.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "evaluationAnswerNumber,evaluationSelectionNumber,evaluationComments,coomnetDate";
            AddParameters(insertCommand, paraNames, evaluationAnswerNumber, evaluationSelectionNumber, evaluationComments, coomnetDate);
            // 
            // InsertAsync 를 호출한다
            EvaluationComment entity = ((EvaluationComment)(await this.GetByKeyAsync(System.Convert.ToInt32(await this.ExecuteScalarAsync(insertCommand)))));
            insertCommand.Dispose();
            return entity;
        }
        
        public int Update(int commentNumber, int evaluationAnswerNumber, int evaluationSelectionNumber, string evaluationComments, System.DateTime coomnetDate)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand updateCmd = DbCommandFactory.CreateDbCommand();
            updateCmd.CommandText = "UPDATE EvaluationComment SET EvaluationAnswerNumber = @evaluationAnswerNumber, Ev" +
                "aluationSelectionNumber = @evaluationSelectionNumber, EvaluationComments = @eval" +
                "uationComments, CoomnetDate = @coomnetDate WHERE CommentNumber = @commentNumber";
            updateCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "commentNumber,evaluationAnswerNumber,evaluationSelectionNumber,evaluationComments" +
                ",coomnetDate";
            AddParameters(updateCmd, paraNames, commentNumber, evaluationAnswerNumber, evaluationSelectionNumber, evaluationComments, coomnetDate);
            // 
            // Update 를 호출한다
            int executeCnt = this.ExecuteNonQuery(updateCmd);
            updateCmd.Dispose();
            return executeCnt;
        }
        
        public async Task<int> UpdateAsync(int commentNumber, int evaluationAnswerNumber, int evaluationSelectionNumber, string evaluationComments, System.DateTime coomnetDate)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand updateCmd = DbCommandFactory.CreateDbCommand();
            updateCmd.CommandText = "UPDATE EvaluationComment SET EvaluationAnswerNumber = @evaluationAnswerNumber, Ev" +
                "aluationSelectionNumber = @evaluationSelectionNumber, EvaluationComments = @eval" +
                "uationComments, CoomnetDate = @coomnetDate WHERE CommentNumber = @commentNumber";
            updateCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "commentNumber,evaluationAnswerNumber,evaluationSelectionNumber,evaluationComments" +
                ",coomnetDate";
            AddParameters(updateCmd, paraNames, commentNumber, evaluationAnswerNumber, evaluationSelectionNumber, evaluationComments, coomnetDate);
            // 
            // Update 를 호출한다
            int executeCnt = await this.ExecuteNonQueryAsync(updateCmd);
            updateCmd.Dispose();
            return executeCnt;
        }
        
        public int Delete(int commentNumber)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand deleteCmd = DbCommandFactory.CreateDbCommand();
            deleteCmd.CommandText = "DELETE FROM EvaluationComment WHERE CommentNumber = @commentNumber";
            deleteCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "commentNumber";
            AddParameters(deleteCmd, paraNames, commentNumber);
            // 
            // Delete 를 호출한다
            int executeCnt = this.ExecuteNonQuery(deleteCmd);
            deleteCmd.Dispose();
            return executeCnt;
        }
        
        public async Task<int> DeleteAsync(int commentNumber)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand deleteCmd = DbCommandFactory.CreateDbCommand();
            deleteCmd.CommandText = "DELETE FROM EvaluationComment WHERE CommentNumber = @commentNumber";
            deleteCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "commentNumber";
            AddParameters(deleteCmd, paraNames, commentNumber);
            // 
            // Delete 를 호출한다
            int executeCnt = await this.ExecuteNonQueryAsync(deleteCmd);
            deleteCmd.Dispose();
            return executeCnt;
        }
    }
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbManager
{
    using System;
    using System.Runtime.Serialization;
    using System.Data;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using System.Transactions;
    using SoftBand.EntityManager;
    
    
    // Table('EvaluationComment') EntitySet class
    // Do not add or change code here.
    [System.Serializable()]
    public partial class EvaluationCommentSet : SoftBand.EntityManager.EntitySet, System.Collections.IEnumerable
    {
        
        // Constructor
        public EvaluationCommentSet() : 
                this(null)
        {
        }
        
        // basic constructor
        protected EvaluationCommentSet(object state)
        {
            this.Setup();
        }
        
        // remoting constructor...
        protected EvaluationCommentSet(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context)
        {
            this.Setup();
        }
        
        public EvaluationCommentBoundCollection Entities
        {
            get
            {
                return this.GetBoundCollection();
            }
        }
        
        // shared object initialization...
        private void Setup()
        {
            this.EntityType = typeof(EvaluationComment);
        }
        
        private EvaluationCommentBoundCollection GetBoundCollection()
        {
            return this.GetBoundCollection(0);
        }
        
        private EvaluationCommentBoundCollection GetBoundCollection(int tableIndex)
        {
            return ((EvaluationCommentBoundCollection)(this.GetBoundCollection(this, tableIndex, typeof(EvaluationCommentBoundCollection))));
        }
        
        public partial class EvaluationCommentBoundCollection : SoftBand.EntityManager.EntityBoundCollection
        {
            
            public new EvaluationComment this[int index]
            {
                get
                {
                    return ((EvaluationComment)(this.EntitySet.GetEntity(this.TableIndex, index)));
                }
            }
        }
    }
}
