//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbManager
{
    using System;
    using System.Runtime.Serialization;
    using System.Data;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using System.Transactions;
    using SoftBand.EntityManager;
    
    
    // Table('EvaluationPassage') Entity class
    // Do not add or change code here.
    [System.Serializable()]
    public partial class EvaluationPassage : SoftBand.EntityManager.Entity
    {
        
        public EvaluationPassage()
        {
            this.DefineColumns(6);
        }
        
        public int EvaluationPassageNumber
        {
            get
            {
                return ((int)(this[0]));
            }
            set
            {
                this[0] = value;
            }
        }
        
        public int EvaluationQuestionNumber
        {
            get
            {
                return ((int)(this[1]));
            }
            set
            {
                this[1] = value;
            }
        }
        
        public string EvaluationPassageCode
        {
            get
            {
                return ((string)(this[2]));
            }
            set
            {
                this[2] = value;
            }
        }
        
        public string EvaluationPassageContents
        {
            get
            {
                return ((string)(this[3]));
            }
            set
            {
                this[3] = value;
            }
        }
        
        public int InputTypeNumber
        {
            get
            {
                return ((int)(this[4]));
            }
            set
            {
                this[4] = value;
            }
        }
        
        public int MeasurementNumber
        {
            get
            {
                return ((int)(this[5]));
            }
            set
            {
                this[5] = value;
            }
        }
        
        public static EvaluationPassageService Service
        {
            get
            {
                return ((EvaluationPassageService)(GetServiceObject(typeof(EvaluationPassage), typeof(EvaluationPassageService))));
            }
        }
        
        public static EvaluationPassageSet GetAll()
        {
            return Service.GetAll();
        }
        
        public static string GetAllJson()
        {
            return Service.GetAllJson();
        }
        
        public static async Task<EvaluationPassageSet> GetAllAsync()
        {
            return await Service.GetAllAsync();
        }
        
        public static async Task<string> GetAllJsonAsync()
        {
            return await Service.GetAllJsonAsync();
        }
        
        public static EvaluationPassageSet GetForEvaluationQuestion(int evaluationQuestionNumber)
        {
            return Service.GetForEvaluationQuestion(evaluationQuestionNumber);
        }
        
        public static EvaluationPassageSet GetForInputType(int inputTypeNumber)
        {
            return Service.GetForInputType(inputTypeNumber);
        }
        
        public static EvaluationPassageSet GetForMeasurement(int measurementNumber)
        {
            return Service.GetForMeasurement(measurementNumber);
        }
        
        public static async Task<EvaluationPassageSet> GetForEvaluationQuestionAsync(int evaluationQuestionNumber)
        {
            return await Service.GetForEvaluationQuestionAsync(evaluationQuestionNumber);
        }
        
        public static async Task<EvaluationPassageSet> GetForInputTypeAsync(int inputTypeNumber)
        {
            return await Service.GetForInputTypeAsync(inputTypeNumber);
        }
        
        public static async Task<EvaluationPassageSet> GetForMeasurementAsync(int measurementNumber)
        {
            return await Service.GetForMeasurementAsync(measurementNumber);
        }
        
        public static string GetForEvaluationQuestionJson(int evaluationQuestionNumber)
        {
            return Service.GetForEvaluationQuestionJson(evaluationQuestionNumber);
        }
        
        public static string GetForInputTypeJson(int inputTypeNumber)
        {
            return Service.GetForInputTypeJson(inputTypeNumber);
        }
        
        public static string GetForMeasurementJson(int measurementNumber)
        {
            return Service.GetForMeasurementJson(measurementNumber);
        }
        
        public static async Task<string> GetForEvaluationQuestionJsonAsync(int evaluationQuestionNumber)
        {
            return await Service.GetForEvaluationQuestionJsonAsync(evaluationQuestionNumber);
        }
        
        public static async Task<string> GetForInputTypeJsonAsync(int inputTypeNumber)
        {
            return await Service.GetForInputTypeJsonAsync(inputTypeNumber);
        }
        
        public static async Task<string> GetForMeasurementJsonAsync(int measurementNumber)
        {
            return await Service.GetForMeasurementJsonAsync(measurementNumber);
        }
        
        public static EvaluationPassage GetByKey(int evaluationPassageNumber)
        {
            return Service.GetByKey(evaluationPassageNumber);
        }
        
        public static string GetByKeyJson(int evaluationPassageNumber)
        {
            return Service.GetByKeyJson(evaluationPassageNumber);
        }
        
        public static async Task<EvaluationPassage> GetByKeyAsync(int evaluationPassageNumber)
        {
            return await Service.GetByKeyAsync(evaluationPassageNumber);
        }
        
        public static async Task<string> GetByKeyJsonAsync(int evaluationPassageNumber)
        {
            return await Service.GetByKeyJsonAsync(evaluationPassageNumber);
        }
        
        public static EvaluationPassage Insert(int evaluationQuestionNumber, string evaluationPassageCode, string evaluationPassageContents, int inputTypeNumber, int measurementNumber)
        {
            // Insert 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            return Service.Insert(evaluationQuestionNumber, evaluationPassageCode, evaluationPassageContents, inputTypeNumber, measurementNumber);
        }
        
        public static async Task<EvaluationPassage> InsertAsync(int evaluationQuestionNumber, string evaluationPassageCode, string evaluationPassageContents, int inputTypeNumber, int measurementNumber)
        {
            // InsertAsync 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            return await Service.InsertAsync(evaluationQuestionNumber, evaluationPassageCode, evaluationPassageContents, inputTypeNumber, measurementNumber);
        }
        
        public new EvaluationPassage Insert()
        {
            // Insert 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            return Insert(EvaluationQuestionNumber, EvaluationPassageCode, EvaluationPassageContents, InputTypeNumber, MeasurementNumber);
        }
        
        public async Task<EvaluationPassage> InsertAsync()
        {
            // Insert 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            return await InsertAsync(EvaluationQuestionNumber, EvaluationPassageCode, EvaluationPassageContents, InputTypeNumber, MeasurementNumber);
        }
        
        public new int Update()
        {
            // 인수를 해당 파라메타에 옮긴다
            int evaluationPassageNumberParam = this.EvaluationPassageNumber;
            int evaluationQuestionNumberParam = this.EvaluationQuestionNumber;
            string evaluationPassageCodeParam = this.EvaluationPassageCode;
            string evaluationPassageContentsParam = this.EvaluationPassageContents;
            int inputTypeNumberParam = this.InputTypeNumber;
            int measurementNumberParam = this.MeasurementNumber;
            // update 실행
            return Service.Update(evaluationPassageNumberParam, evaluationQuestionNumberParam, evaluationPassageCodeParam, evaluationPassageContentsParam, inputTypeNumberParam, measurementNumberParam);
        }
        
        public async Task<int> UpdateAsync()
        {
            // 인수를 해당 파라메타에 옮긴다
            int evaluationPassageNumberParam = this.EvaluationPassageNumber;
            int evaluationQuestionNumberParam = this.EvaluationQuestionNumber;
            string evaluationPassageCodeParam = this.EvaluationPassageCode;
            string evaluationPassageContentsParam = this.EvaluationPassageContents;
            int inputTypeNumberParam = this.InputTypeNumber;
            int measurementNumberParam = this.MeasurementNumber;
            return await Service.UpdateAsync(evaluationPassageNumberParam, evaluationQuestionNumberParam, evaluationPassageCodeParam, evaluationPassageContentsParam, inputTypeNumberParam, measurementNumberParam);
        }
        
        public static int Update(int evaluationPassageNumber, int evaluationQuestionNumber, string evaluationPassageCode, string evaluationPassageContents, int inputTypeNumber, int measurementNumber)
        {
            return Service.Update(evaluationPassageNumber, evaluationQuestionNumber, evaluationPassageCode, evaluationPassageContents, inputTypeNumber, measurementNumber);
        }
        
        public static async Task<int> UpdateAsync(int evaluationPassageNumber, int evaluationQuestionNumber, string evaluationPassageCode, string evaluationPassageContents, int inputTypeNumber, int measurementNumber)
        {
            return await Service.UpdateAsync(evaluationPassageNumber, evaluationQuestionNumber, evaluationPassageCode, evaluationPassageContents, inputTypeNumber, measurementNumber);
        }
        
        public static int Delete(int evaluationPassageNumber)
        {
            return Service.Delete(evaluationPassageNumber);
        }
        
        public static async Task<int> DeleteAsync(int evaluationPassageNumber)
        {
            return await Service.DeleteAsync(evaluationPassageNumber);
        }
        
        public new int Delete()
        {
            return Service.Delete(EvaluationPassageNumber);
        }
        
        public async Task<int> DeleteAsync()
        {
            return await Service.DeleteAsync(EvaluationPassageNumber);
        }
    }
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbManager
{
    using System;
    using System.Runtime.Serialization;
    using System.Data;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using System.Transactions;
    using SoftBand.EntityManager;
    
    
    // Table('EvaluationPassage')  Service class
    // Do not add or change code here.
    public partial class EvaluationPassageService : SoftBand.EntityManager.Service
    {
        
        public EvaluationPassageSet GetAll()
        {
            return ((EvaluationPassageSet)(this.GetAll("EvaluationPassage", typeof(EvaluationPassageSet))));
        }
        
        public string GetAllJson()
        {
            return this.GetAllJson("EvaluationPassage");
        }
        
        public async Task<EvaluationPassageSet> GetAllAsync()
        {
            return ((EvaluationPassageSet)(await this.GetAllAsync("EvaluationPassage", typeof(EvaluationPassageSet))));
        }
        
        public async Task<string> GetAllJsonAsync()
        {
            return await this.GetAllJsonAsync("EvaluationPassage");
        }
        
        public EvaluationPassageSet GetForEvaluationQuestion(int evaluationQuestionNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [EvaluationPassage] WHERE EvaluationQuestionNumber = @evaluationQue" +
                "stionNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "evaluationQuestionNumber";
            AddParameters(selectCmd, paraNames, evaluationQuestionNumber);
            EvaluationPassageSet entitySet = ((EvaluationPassageSet)(this.GetEntitySet(selectCmd, typeof(EvaluationPassageSet))));
            selectCmd.Dispose();
            return entitySet;
        }
        
        public EvaluationPassageSet GetForInputType(int inputTypeNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [EvaluationPassage] WHERE InputTypeNumber = @inputTypeNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "inputTypeNumber";
            AddParameters(selectCmd, paraNames, inputTypeNumber);
            EvaluationPassageSet entitySet = ((EvaluationPassageSet)(this.GetEntitySet(selectCmd, typeof(EvaluationPassageSet))));
            selectCmd.Dispose();
            return entitySet;
        }
        
        public EvaluationPassageSet GetForMeasurement(int measurementNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [EvaluationPassage] WHERE MeasurementNumber = @measurementNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "measurementNumber";
            AddParameters(selectCmd, paraNames, measurementNumber);
            EvaluationPassageSet entitySet = ((EvaluationPassageSet)(this.GetEntitySet(selectCmd, typeof(EvaluationPassageSet))));
            selectCmd.Dispose();
            return entitySet;
        }
        
        public async Task<EvaluationPassageSet> GetForEvaluationQuestionAsync(int evaluationQuestionNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [EvaluationPassage] WHERE EvaluationQuestionNumber = @evaluationQue" +
                "stionNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "evaluationQuestionNumber";
            AddParameters(selectCmd, paraNames, evaluationQuestionNumber);
            EvaluationPassageSet entitySet = ((EvaluationPassageSet)(await this.GetEntitySetAsync(selectCmd, typeof(EvaluationPassageSet))));
            selectCmd.Dispose();
            return entitySet;
        }
        
        public async Task<EvaluationPassageSet> GetForInputTypeAsync(int inputTypeNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [EvaluationPassage] WHERE InputTypeNumber = @inputTypeNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "inputTypeNumber";
            AddParameters(selectCmd, paraNames, inputTypeNumber);
            EvaluationPassageSet entitySet = ((EvaluationPassageSet)(await this.GetEntitySetAsync(selectCmd, typeof(EvaluationPassageSet))));
            selectCmd.Dispose();
            return entitySet;
        }
        
        public async Task<EvaluationPassageSet> GetForMeasurementAsync(int measurementNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [EvaluationPassage] WHERE MeasurementNumber = @measurementNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "measurementNumber";
            AddParameters(selectCmd, paraNames, measurementNumber);
            EvaluationPassageSet entitySet = ((EvaluationPassageSet)(await this.GetEntitySetAsync(selectCmd, typeof(EvaluationPassageSet))));
            selectCmd.Dispose();
            return entitySet;
        }
        
        public string GetForEvaluationQuestionJson(int evaluationQuestionNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [EvaluationPassage] WHERE EvaluationQuestionNumber = @evaluationQue" +
                "stionNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "evaluationQuestionNumber";
            AddParameters(selectCmd, paraNames, evaluationQuestionNumber);
            return  this.GetJsonDataSet(selectCmd);
        }
        
        public string GetForInputTypeJson(int inputTypeNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [EvaluationPassage] WHERE InputTypeNumber = @inputTypeNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "inputTypeNumber";
            AddParameters(selectCmd, paraNames, inputTypeNumber);
            return  this.GetJsonDataSet(selectCmd);
        }
        
        public string GetForMeasurementJson(int measurementNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [EvaluationPassage] WHERE MeasurementNumber = @measurementNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "measurementNumber";
            AddParameters(selectCmd, paraNames, measurementNumber);
            return  this.GetJsonDataSet(selectCmd);
        }
        
        public async Task<string> GetForEvaluationQuestionJsonAsync(int evaluationQuestionNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [EvaluationPassage] WHERE EvaluationQuestionNumber = @evaluationQue" +
                "stionNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "evaluationQuestionNumber";
            AddParameters(selectCmd, paraNames, evaluationQuestionNumber);
            return await this.GetJsonDataSetAsync(selectCmd);
        }
        
        public async Task<string> GetForInputTypeJsonAsync(int inputTypeNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [EvaluationPassage] WHERE InputTypeNumber = @inputTypeNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "inputTypeNumber";
            AddParameters(selectCmd, paraNames, inputTypeNumber);
            return await this.GetJsonDataSetAsync(selectCmd);
        }
        
        public async Task<string> GetForMeasurementJsonAsync(int measurementNumber)
        {
            // Sql Command Statement
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM [EvaluationPassage] WHERE MeasurementNumber = @measurementNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Make parameters
            string paraNames = "measurementNumber";
            AddParameters(selectCmd, paraNames, measurementNumber);
            return await this.GetJsonDataSetAsync(selectCmd);
        }
        
        public EvaluationPassage GetByKey(int evaluationPassageNumber)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM EvaluationPassage WHERE EvaluationPassageNumber = @evaluationPassag" +
                "eNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "evaluationPassageNumber";
            AddParameters(selectCmd, paraNames, evaluationPassageNumber);
            // 
            EvaluationPassage entity = ((EvaluationPassage)(this.GetEntity(selectCmd, typeof(EvaluationPassageSet))));
            selectCmd.Dispose();
            return entity;
        }
        
        public  string GetByKeyJson(int evaluationPassageNumber)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM EvaluationPassage WHERE EvaluationPassageNumber = @evaluationPassag" +
                "eNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "evaluationPassageNumber";
            AddParameters(selectCmd, paraNames, evaluationPassageNumber);
            // 
            return this.GetJsonDataSet(selectCmd);
        }
        
        public async Task<EvaluationPassage> GetByKeyAsync(int evaluationPassageNumber)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM EvaluationPassage WHERE EvaluationPassageNumber = @evaluationPassag" +
                "eNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "evaluationPassageNumber";
            AddParameters(selectCmd, paraNames, evaluationPassageNumber);
            // 
            // GetByKeyAsync 를 호출한다
            EvaluationPassage entity = ((EvaluationPassage)(await this.GetEntityAsync(selectCmd, typeof(EvaluationPassageSet))));
            selectCmd.Dispose();
            return entity;
        }
        
        public async Task<string> GetByKeyJsonAsync(int evaluationPassageNumber)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM EvaluationPassage WHERE EvaluationPassageNumber = @evaluationPassag" +
                "eNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "evaluationPassageNumber";
            AddParameters(selectCmd, paraNames, evaluationPassageNumber);
            // 
            return await this.GetJsonDataSetAsync(selectCmd);
        }
        
        public EvaluationPassage Insert(int evaluationQuestionNumber, string evaluationPassageCode, string evaluationPassageContents, int inputTypeNumber, int measurementNumber)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand insertCommand = DbCommandFactory.CreateDbCommand();
            insertCommand.CommandText = @"INSERT INTO EvaluationPassage(EvaluationQuestionNumber, EvaluationPassageCode, EvaluationPassageContents, InputTypeNumber, MeasurementNumber) OUTPUT INSERTED.EvaluationPassageNumber
VALUES (@evaluationQuestionNumber, @evaluationPassageCode, @evaluationPassageContents, @inputTypeNumber, @measurementNumber) ";
            insertCommand.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "evaluationQuestionNumber,evaluationPassageCode,evaluationPassageContents,inputTyp" +
                "eNumber,measurementNumber";
            AddParameters(insertCommand, paraNames, evaluationQuestionNumber, evaluationPassageCode, evaluationPassageContents, inputTypeNumber, measurementNumber);
            // 
            // Insert 를 호출한다
            EvaluationPassage entity = ((EvaluationPassage)(this.GetByKey(System.Convert.ToInt32(this.ExecuteScalar(insertCommand)))));
            insertCommand.Dispose();
            return entity;
        }
        
        public async Task<EvaluationPassage> InsertAsync(int evaluationQuestionNumber, string evaluationPassageCode, string evaluationPassageContents, int inputTypeNumber, int measurementNumber)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand insertCommand = DbCommandFactory.CreateDbCommand();
            insertCommand.CommandText = @"INSERT INTO EvaluationPassage(EvaluationQuestionNumber, EvaluationPassageCode, EvaluationPassageContents, InputTypeNumber, MeasurementNumber) OUTPUT INSERTED.EvaluationPassageNumber
VALUES (@evaluationQuestionNumber, @evaluationPassageCode, @evaluationPassageContents, @inputTypeNumber, @measurementNumber) ";
            insertCommand.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "evaluationQuestionNumber,evaluationPassageCode,evaluationPassageContents,inputTyp" +
                "eNumber,measurementNumber";
            AddParameters(insertCommand, paraNames, evaluationQuestionNumber, evaluationPassageCode, evaluationPassageContents, inputTypeNumber, measurementNumber);
            // 
            // InsertAsync 를 호출한다
            EvaluationPassage entity = ((EvaluationPassage)(await this.GetByKeyAsync(System.Convert.ToInt32(await this.ExecuteScalarAsync(insertCommand)))));
            insertCommand.Dispose();
            return entity;
        }
        
        public int Update(int evaluationPassageNumber, int evaluationQuestionNumber, string evaluationPassageCode, string evaluationPassageContents, int inputTypeNumber, int measurementNumber)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand updateCmd = DbCommandFactory.CreateDbCommand();
            updateCmd.CommandText = @"UPDATE EvaluationPassage SET EvaluationQuestionNumber = @evaluationQuestionNumber, EvaluationPassageCode = @evaluationPassageCode, EvaluationPassageContents = @evaluationPassageContents, InputTypeNumber = @inputTypeNumber, MeasurementNumber = @measurementNumber WHERE EvaluationPassageNumber = @evaluationPassageNumber";
            updateCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "evaluationPassageNumber,evaluationQuestionNumber,evaluationPassageCode,evaluation" +
                "PassageContents,inputTypeNumber,measurementNumber";
            AddParameters(updateCmd, paraNames, evaluationPassageNumber, evaluationQuestionNumber, evaluationPassageCode, evaluationPassageContents, inputTypeNumber, measurementNumber);
            // 
            // Update 를 호출한다
            int executeCnt = this.ExecuteNonQuery(updateCmd);
            updateCmd.Dispose();
            return executeCnt;
        }
        
        public async Task<int> UpdateAsync(int evaluationPassageNumber, int evaluationQuestionNumber, string evaluationPassageCode, string evaluationPassageContents, int inputTypeNumber, int measurementNumber)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand updateCmd = DbCommandFactory.CreateDbCommand();
            updateCmd.CommandText = @"UPDATE EvaluationPassage SET EvaluationQuestionNumber = @evaluationQuestionNumber, EvaluationPassageCode = @evaluationPassageCode, EvaluationPassageContents = @evaluationPassageContents, InputTypeNumber = @inputTypeNumber, MeasurementNumber = @measurementNumber WHERE EvaluationPassageNumber = @evaluationPassageNumber";
            updateCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "evaluationPassageNumber,evaluationQuestionNumber,evaluationPassageCode,evaluation" +
                "PassageContents,inputTypeNumber,measurementNumber";
            AddParameters(updateCmd, paraNames, evaluationPassageNumber, evaluationQuestionNumber, evaluationPassageCode, evaluationPassageContents, inputTypeNumber, measurementNumber);
            // 
            // Update 를 호출한다
            int executeCnt = await this.ExecuteNonQueryAsync(updateCmd);
            updateCmd.Dispose();
            return executeCnt;
        }
        
        public int Delete(int evaluationPassageNumber)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand deleteCmd = DbCommandFactory.CreateDbCommand();
            deleteCmd.CommandText = "DELETE FROM EvaluationPassage WHERE EvaluationPassageNumber = @evaluationPassageN" +
                "umber";
            deleteCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "evaluationPassageNumber";
            AddParameters(deleteCmd, paraNames, evaluationPassageNumber);
            // 
            // Delete 를 호출한다
            int executeCnt = this.ExecuteNonQuery(deleteCmd);
            deleteCmd.Dispose();
            return executeCnt;
        }
        
        public async Task<int> DeleteAsync(int evaluationPassageNumber)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand deleteCmd = DbCommandFactory.CreateDbCommand();
            deleteCmd.CommandText = "DELETE FROM EvaluationPassage WHERE EvaluationPassageNumber = @evaluationPassageN" +
                "umber";
            deleteCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "evaluationPassageNumber";
            AddParameters(deleteCmd, paraNames, evaluationPassageNumber);
            // 
            // Delete 를 호출한다
            int executeCnt = await this.ExecuteNonQueryAsync(deleteCmd);
            deleteCmd.Dispose();
            return executeCnt;
        }
    }
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbManager
{
    using System;
    using System.Runtime.Serialization;
    using System.Data;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using System.Transactions;
    using SoftBand.EntityManager;
    
    
    // Table('EvaluationPassage') EntitySet class
    // Do not add or change code here.
    [System.Serializable()]
    public partial class EvaluationPassageSet : SoftBand.EntityManager.EntitySet, System.Collections.IEnumerable
    {
        
        // Constructor
        public EvaluationPassageSet() : 
                this(null)
        {
        }
        
        // basic constructor
        protected EvaluationPassageSet(object state)
        {
            this.Setup();
        }
        
        // remoting constructor...
        protected EvaluationPassageSet(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context)
        {
            this.Setup();
        }
        
        public EvaluationPassageBoundCollection Entities
        {
            get
            {
                return this.GetBoundCollection();
            }
        }
        
        // shared object initialization...
        private void Setup()
        {
            this.EntityType = typeof(EvaluationPassage);
        }
        
        private EvaluationPassageBoundCollection GetBoundCollection()
        {
            return this.GetBoundCollection(0);
        }
        
        private EvaluationPassageBoundCollection GetBoundCollection(int tableIndex)
        {
            return ((EvaluationPassageBoundCollection)(this.GetBoundCollection(this, tableIndex, typeof(EvaluationPassageBoundCollection))));
        }
        
        public partial class EvaluationPassageBoundCollection : SoftBand.EntityManager.EntityBoundCollection
        {
            
            public new EvaluationPassage this[int index]
            {
                get
                {
                    return ((EvaluationPassage)(this.EntitySet.GetEntity(this.TableIndex, index)));
                }
            }
        }
    }
}
