//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbManager
{
    using System;
    using System.Runtime.Serialization;
    using System.Data;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using System.Transactions;
    using SoftBand.EntityManager;
    
    
    // Table('Measurement') Entity class
    // Do not add or change code here.
    [System.Serializable()]
    public partial class Measurement : SoftBand.EntityManager.Entity
    {
        
        public Measurement()
        {
            this.DefineColumns(3);
        }
        
        public int MeasurementNumber
        {
            get
            {
                return ((int)(this[0]));
            }
            set
            {
                this[0] = value;
            }
        }
        
        public string MeasurementCode
        {
            get
            {
                return ((string)(this[1]));
            }
            set
            {
                this[1] = value;
            }
        }
        
        public string MeasurementName
        {
            get
            {
                return ((string)(this[2]));
            }
            set
            {
                this[2] = value;
            }
        }
        
        public static MeasurementService Service
        {
            get
            {
                return ((MeasurementService)(GetServiceObject(typeof(Measurement), typeof(MeasurementService))));
            }
        }
        
        public static MeasurementSet GetAll()
        {
            return Service.GetAll();
        }
        
        public static string GetAllJson()
        {
            return Service.GetAllJson();
        }
        
        public static async Task<MeasurementSet> GetAllAsync()
        {
            return await Service.GetAllAsync();
        }
        
        public static async Task<string> GetAllJsonAsync()
        {
            return await Service.GetAllJsonAsync();
        }
        
        public static Measurement GetByKey(int measurementNumber)
        {
            return Service.GetByKey(measurementNumber);
        }
        
        public static string GetByKeyJson(int measurementNumber)
        {
            return Service.GetByKeyJson(measurementNumber);
        }
        
        public static async Task<Measurement> GetByKeyAsync(int measurementNumber)
        {
            return await Service.GetByKeyAsync(measurementNumber);
        }
        
        public static async Task<string> GetByKeyJsonAsync(int measurementNumber)
        {
            return await Service.GetByKeyJsonAsync(measurementNumber);
        }
        
        public static Measurement Insert(string measurementCode, string measurementName)
        {
            // Insert 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            return Service.Insert(measurementCode, measurementName);
        }
        
        public static async Task<Measurement> InsertAsync(string measurementCode, string measurementName)
        {
            // InsertAsync 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            return await Service.InsertAsync(measurementCode, measurementName);
        }
        
        public new Measurement Insert()
        {
            // Insert 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            return Insert(MeasurementCode, MeasurementName);
        }
        
        public async Task<Measurement> InsertAsync()
        {
            // Insert 명령은 Table Key가 자동 발생키로 구성되어 있지 않는 Table에 
            // 제한적으로 사용할 수 있습니다
            // 
            return await InsertAsync(MeasurementCode, MeasurementName);
        }
        
        public new int Update()
        {
            // 인수를 해당 파라메타에 옮긴다
            int measurementNumberParam = this.MeasurementNumber;
            string measurementCodeParam = this.MeasurementCode;
            string measurementNameParam = this.MeasurementName;
            // update 실행
            return Service.Update(measurementNumberParam, measurementCodeParam, measurementNameParam);
        }
        
        public async Task<int> UpdateAsync()
        {
            // 인수를 해당 파라메타에 옮긴다
            int measurementNumberParam = this.MeasurementNumber;
            string measurementCodeParam = this.MeasurementCode;
            string measurementNameParam = this.MeasurementName;
            return await Service.UpdateAsync(measurementNumberParam, measurementCodeParam, measurementNameParam);
        }
        
        public static int Update(int measurementNumber, string measurementCode, string measurementName)
        {
            return Service.Update(measurementNumber, measurementCode, measurementName);
        }
        
        public static async Task<int> UpdateAsync(int measurementNumber, string measurementCode, string measurementName)
        {
            return await Service.UpdateAsync(measurementNumber, measurementCode, measurementName);
        }
        
        public static int Delete(int measurementNumber)
        {
            return Service.Delete(measurementNumber);
        }
        
        public static async Task<int> DeleteAsync(int measurementNumber)
        {
            return await Service.DeleteAsync(measurementNumber);
        }
        
        public new int Delete()
        {
            return Service.Delete(MeasurementNumber);
        }
        
        public async Task<int> DeleteAsync()
        {
            return await Service.DeleteAsync(MeasurementNumber);
        }
    }
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbManager
{
    using System;
    using System.Runtime.Serialization;
    using System.Data;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using System.Transactions;
    using SoftBand.EntityManager;
    
    
    // Table('Measurement')  Service class
    // Do not add or change code here.
    public partial class MeasurementService : SoftBand.EntityManager.Service
    {
        
        public MeasurementSet GetAll()
        {
            return ((MeasurementSet)(this.GetAll("Measurement", typeof(MeasurementSet))));
        }
        
        public string GetAllJson()
        {
            return this.GetAllJson("Measurement");
        }
        
        public async Task<MeasurementSet> GetAllAsync()
        {
            return ((MeasurementSet)(await this.GetAllAsync("Measurement", typeof(MeasurementSet))));
        }
        
        public async Task<string> GetAllJsonAsync()
        {
            return await this.GetAllJsonAsync("Measurement");
        }
        
        public Measurement GetByKey(int measurementNumber)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM Measurement WHERE MeasurementNumber = @measurementNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "measurementNumber";
            AddParameters(selectCmd, paraNames, measurementNumber);
            // 
            Measurement entity = ((Measurement)(this.GetEntity(selectCmd, typeof(MeasurementSet))));
            selectCmd.Dispose();
            return entity;
        }
        
        public  string GetByKeyJson(int measurementNumber)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM Measurement WHERE MeasurementNumber = @measurementNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "measurementNumber";
            AddParameters(selectCmd, paraNames, measurementNumber);
            // 
            return this.GetJsonDataSet(selectCmd);
        }
        
        public async Task<Measurement> GetByKeyAsync(int measurementNumber)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM Measurement WHERE MeasurementNumber = @measurementNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "measurementNumber";
            AddParameters(selectCmd, paraNames, measurementNumber);
            // 
            // GetByKeyAsync 를 호출한다
            Measurement entity = ((Measurement)(await this.GetEntityAsync(selectCmd, typeof(MeasurementSet))));
            selectCmd.Dispose();
            return entity;
        }
        
        public async Task<string> GetByKeyJsonAsync(int measurementNumber)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand selectCmd = DbCommandFactory.CreateDbCommand();
            selectCmd.CommandText = "SELECT * FROM Measurement WHERE MeasurementNumber = @measurementNumber";
            selectCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "measurementNumber";
            AddParameters(selectCmd, paraNames, measurementNumber);
            // 
            return await this.GetJsonDataSetAsync(selectCmd);
        }
        
        public Measurement Insert(string measurementCode, string measurementName)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand insertCommand = DbCommandFactory.CreateDbCommand();
            insertCommand.CommandText = "INSERT INTO Measurement(MeasurementCode, MeasurementName) OUTPUT INSERTED.Measure" +
                "mentNumber\r\nVALUES (@measurementCode, @measurementName) ";
            insertCommand.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "measurementCode,measurementName";
            AddParameters(insertCommand, paraNames, measurementCode, measurementName);
            // 
            // Insert 를 호출한다
            Measurement entity = ((Measurement)(this.GetByKey(System.Convert.ToInt32(this.ExecuteScalar(insertCommand)))));
            insertCommand.Dispose();
            return entity;
        }
        
        public async Task<Measurement> InsertAsync(string measurementCode, string measurementName)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand insertCommand = DbCommandFactory.CreateDbCommand();
            insertCommand.CommandText = "INSERT INTO Measurement(MeasurementCode, MeasurementName) OUTPUT INSERTED.Measure" +
                "mentNumber\r\nVALUES (@measurementCode, @measurementName) ";
            insertCommand.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "measurementCode,measurementName";
            AddParameters(insertCommand, paraNames, measurementCode, measurementName);
            // 
            // InsertAsync 를 호출한다
            Measurement entity = ((Measurement)(await this.GetByKeyAsync(System.Convert.ToInt32(await this.ExecuteScalarAsync(insertCommand)))));
            insertCommand.Dispose();
            return entity;
        }
        
        public int Update(int measurementNumber, string measurementCode, string measurementName)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand updateCmd = DbCommandFactory.CreateDbCommand();
            updateCmd.CommandText = "UPDATE Measurement SET MeasurementCode = @measurementCode, MeasurementName = @mea" +
                "surementName WHERE MeasurementNumber = @measurementNumber";
            updateCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "measurementNumber,measurementCode,measurementName";
            AddParameters(updateCmd, paraNames, measurementNumber, measurementCode, measurementName);
            // 
            // Update 를 호출한다
            int executeCnt = this.ExecuteNonQuery(updateCmd);
            updateCmd.Dispose();
            return executeCnt;
        }
        
        public async Task<int> UpdateAsync(int measurementNumber, string measurementCode, string measurementName)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand updateCmd = DbCommandFactory.CreateDbCommand();
            updateCmd.CommandText = "UPDATE Measurement SET MeasurementCode = @measurementCode, MeasurementName = @mea" +
                "surementName WHERE MeasurementNumber = @measurementNumber";
            updateCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "measurementNumber,measurementCode,measurementName";
            AddParameters(updateCmd, paraNames, measurementNumber, measurementCode, measurementName);
            // 
            // Update 를 호출한다
            int executeCnt = await this.ExecuteNonQueryAsync(updateCmd);
            updateCmd.Dispose();
            return executeCnt;
        }
        
        public int Delete(int measurementNumber)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand deleteCmd = DbCommandFactory.CreateDbCommand();
            deleteCmd.CommandText = "DELETE FROM Measurement WHERE MeasurementNumber = @measurementNumber";
            deleteCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "measurementNumber";
            AddParameters(deleteCmd, paraNames, measurementNumber);
            // 
            // Delete 를 호출한다
            int executeCnt = this.ExecuteNonQuery(deleteCmd);
            deleteCmd.Dispose();
            return executeCnt;
        }
        
        public async Task<int> DeleteAsync(int measurementNumber)
        {
            // IDbCommand 명령문
            System.Data.IDbCommand deleteCmd = DbCommandFactory.CreateDbCommand();
            deleteCmd.CommandText = "DELETE FROM Measurement WHERE MeasurementNumber = @measurementNumber";
            deleteCmd.CommandType = System.Data.CommandType.Text;
            // 
            // Add parameter
            string paraNames = "measurementNumber";
            AddParameters(deleteCmd, paraNames, measurementNumber);
            // 
            // Delete 를 호출한다
            int executeCnt = await this.ExecuteNonQueryAsync(deleteCmd);
            deleteCmd.Dispose();
            return executeCnt;
        }
    }
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbManager
{
    using System;
    using System.Runtime.Serialization;
    using System.Data;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using System.Transactions;
    using SoftBand.EntityManager;
    
    
    // Table('Measurement') EntitySet class
    // Do not add or change code here.
    [System.Serializable()]
    public partial class MeasurementSet : SoftBand.EntityManager.EntitySet, System.Collections.IEnumerable
    {
        
        // Constructor
        public MeasurementSet() : 
                this(null)
        {
        }
        
        // basic constructor
        protected MeasurementSet(object state)
        {
            this.Setup();
        }
        
        // remoting constructor...
        protected MeasurementSet(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context)
        {
            this.Setup();
        }
        
        public MeasurementBoundCollection Entities
        {
            get
            {
                return this.GetBoundCollection();
            }
        }
        
        // shared object initialization...
        private void Setup()
        {
            this.EntityType = typeof(Measurement);
        }
        
        private MeasurementBoundCollection GetBoundCollection()
        {
            return this.GetBoundCollection(0);
        }
        
        private MeasurementBoundCollection GetBoundCollection(int tableIndex)
        {
            return ((MeasurementBoundCollection)(this.GetBoundCollection(this, tableIndex, typeof(MeasurementBoundCollection))));
        }
        
        public partial class MeasurementBoundCollection : SoftBand.EntityManager.EntityBoundCollection
        {
            
            public new Measurement this[int index]
            {
                get
                {
                    return ((Measurement)(this.EntitySet.GetEntity(this.TableIndex, index)));
                }
            }
        }
    }
}
